// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0 (
        ap_clk,
        ap_rst,
        data_0_V_read,
        data_1_V_read,
        data_2_V_read,
        data_3_V_read,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_return_8,
        ap_return_9,
        ap_return_10,
        ap_return_11,
        ap_ce
);


input   ap_clk;
input   ap_rst;
input  [15:0] data_0_V_read;
input  [15:0] data_1_V_read;
input  [15:0] data_2_V_read;
input  [15:0] data_3_V_read;
output  [15:0] ap_return_0;
output  [15:0] ap_return_1;
output  [15:0] ap_return_2;
output  [15:0] ap_return_3;
output  [15:0] ap_return_4;
output  [15:0] ap_return_5;
output  [15:0] ap_return_6;
output  [15:0] ap_return_7;
output  [15:0] ap_return_8;
output  [15:0] ap_return_9;
output  [15:0] ap_return_10;
output  [15:0] ap_return_11;
input   ap_ce;

reg[15:0] ap_return_0;
reg[15:0] ap_return_1;
reg[15:0] ap_return_2;
reg[15:0] ap_return_3;
reg[15:0] ap_return_4;
reg[15:0] ap_return_5;
reg[15:0] ap_return_6;
reg[15:0] ap_return_7;
reg[15:0] ap_return_8;
reg[15:0] ap_return_9;
reg[15:0] ap_return_10;
reg[15:0] ap_return_11;

reg  signed [15:0] data_3_V_read_6_reg_7799;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_pp0_stage0_11001;
reg  signed [15:0] data_3_V_read_6_reg_7799_pp0_iter1_reg;
reg  signed [15:0] data_2_V_read_6_reg_7806;
reg  signed [15:0] data_1_V_read_6_reg_7814;
reg  signed [15:0] data_0_V_read_6_reg_7822;
reg  signed [15:0] data_0_V_read_6_reg_7822_pp0_iter1_reg;
wire  signed [24:0] sext_ln1118_35_fu_6710_p1;
wire  signed [25:0] sext_ln1118_36_fu_6716_p1;
wire  signed [22:0] sext_ln1118_37_fu_6725_p1;
wire  signed [24:0] sext_ln1118_45_fu_6741_p1;
wire  signed [25:0] sext_ln1118_46_fu_6748_p1;
wire  signed [23:0] sext_ln1118_47_fu_6756_p1;
wire  signed [24:0] sext_ln1118_fu_6762_p1;
wire  signed [25:0] sext_ln1118_28_fu_6776_p1;
wire  signed [24:0] sext_ln1118_33_fu_6784_p1;
wire  signed [25:0] sext_ln1118_34_fu_6793_p1;
reg   [8:0] trunc_ln708_45_reg_7926;
reg   [8:0] trunc_ln708_45_reg_7926_pp0_iter2_reg;
reg   [12:0] trunc_ln708_48_reg_7931;
reg   [13:0] trunc_ln708_49_reg_7936;
reg   [10:0] trunc_ln708_50_reg_7941;
reg   [15:0] trunc_ln708_51_reg_7946;
reg   [15:0] trunc_ln708_52_reg_7951;
reg   [14:0] trunc_ln708_53_reg_7956;
reg   [15:0] trunc_ln708_54_reg_7961;
reg   [15:0] trunc_ln708_55_reg_7966;
reg   [14:0] trunc_ln708_56_reg_7971;
reg   [12:0] trunc_ln708_57_reg_7976;
reg   [14:0] trunc_ln708_58_reg_7981;
reg   [15:0] trunc_ln708_59_reg_7986;
reg   [15:0] trunc_ln708_60_reg_7991;
reg   [15:0] trunc_ln708_61_reg_7996;
reg   [14:0] trunc_ln708_62_reg_8001;
reg   [15:0] trunc_ln708_63_reg_8006;
reg   [15:0] trunc_ln708_64_reg_8011;
reg   [12:0] trunc_ln708_65_reg_8016;
reg   [13:0] trunc_ln708_66_reg_8021;
reg   [14:0] trunc_ln708_67_reg_8026;
reg   [14:0] trunc_ln708_69_reg_8031;
reg   [13:0] trunc_ln708_71_reg_8036;
reg   [8:0] trunc_ln_reg_8041;
reg   [15:0] trunc_ln708_25_reg_8046;
reg   [11:0] trunc_ln708_26_reg_8051;
reg   [14:0] trunc_ln708_27_reg_8056;
reg   [14:0] trunc_ln708_28_reg_8061;
reg   [14:0] trunc_ln708_29_reg_8066;
reg   [15:0] trunc_ln708_30_reg_8071;
reg   [14:0] trunc_ln708_31_reg_8076;
reg   [14:0] trunc_ln708_32_reg_8081;
reg   [14:0] trunc_ln708_33_reg_8086;
reg   [14:0] trunc_ln708_34_reg_8091;
reg   [14:0] trunc_ln708_35_reg_8096;
reg   [15:0] trunc_ln708_36_reg_8101;
reg   [14:0] trunc_ln708_37_reg_8106;
reg   [15:0] trunc_ln708_38_reg_8111;
reg   [14:0] trunc_ln708_39_reg_8116;
reg   [14:0] trunc_ln708_40_reg_8121;
reg   [15:0] trunc_ln708_41_reg_8126;
reg   [14:0] trunc_ln708_42_reg_8131;
reg   [14:0] trunc_ln708_43_reg_8136;
reg   [14:0] trunc_ln708_44_reg_8141;
reg   [15:0] trunc_ln708_46_reg_8146;
reg   [15:0] trunc_ln708_47_reg_8151;
wire   [15:0] add_ln703_15_fu_7488_p2;
reg   [15:0] add_ln703_15_reg_8156;
wire   [15:0] add_ln703_18_fu_7493_p2;
reg   [15:0] add_ln703_18_reg_8161;
wire   [15:0] add_ln703_21_fu_7498_p2;
reg   [15:0] add_ln703_21_reg_8166;
wire   [15:0] add_ln703_24_fu_7504_p2;
reg   [15:0] add_ln703_24_reg_8171;
wire   [15:0] add_ln703_27_fu_7508_p2;
reg   [15:0] add_ln703_27_reg_8176;
wire   [15:0] add_ln703_30_fu_7512_p2;
reg   [15:0] add_ln703_30_reg_8181;
wire   [15:0] add_ln703_33_fu_7518_p2;
reg   [15:0] add_ln703_33_reg_8186;
wire   [15:0] add_ln703_36_fu_7523_p2;
reg   [15:0] add_ln703_36_reg_8191;
wire   [15:0] add_ln703_39_fu_7528_p2;
reg   [15:0] add_ln703_39_reg_8196;
wire   [15:0] add_ln703_42_fu_7534_p2;
reg   [15:0] add_ln703_42_reg_8201;
wire   [15:0] add_ln703_45_fu_7540_p2;
reg   [15:0] add_ln703_45_reg_8206;
wire   [15:0] add_ln703_48_fu_7546_p2;
reg   [15:0] add_ln703_48_reg_8211;
wire  signed [15:0] grp_fu_182_p0;
wire  signed [10:0] grp_fu_182_p1;
wire    ap_block_pp0_stage0;
wire  signed [15:0] grp_fu_183_p0;
wire  signed [8:0] grp_fu_183_p1;
wire  signed [15:0] grp_fu_184_p0;
wire  signed [7:0] grp_fu_184_p1;
wire  signed [15:0] grp_fu_185_p0;
wire  signed [8:0] grp_fu_185_p1;
wire  signed [15:0] grp_fu_186_p0;
wire  signed [10:0] grp_fu_186_p1;
wire  signed [7:0] grp_fu_187_p1;
wire  signed [15:0] grp_fu_188_p0;
wire  signed [8:0] grp_fu_188_p1;
wire  signed [15:0] grp_fu_190_p0;
wire   [9:0] grp_fu_190_p1;
wire  signed [15:0] grp_fu_193_p0;
wire   [9:0] grp_fu_193_p1;
wire  signed [15:0] grp_fu_194_p0;
wire  signed [9:0] grp_fu_194_p1;
wire  signed [15:0] grp_fu_195_p0;
wire   [8:0] grp_fu_195_p1;
wire  signed [15:0] grp_fu_196_p0;
wire  signed [9:0] grp_fu_196_p1;
wire  signed [5:0] grp_fu_197_p1;
wire  signed [15:0] grp_fu_198_p0;
wire  signed [8:0] grp_fu_198_p1;
wire  signed [6:0] grp_fu_199_p1;
wire  signed [15:0] grp_fu_200_p0;
wire   [8:0] grp_fu_200_p1;
wire  signed [15:0] grp_fu_201_p0;
wire   [8:0] grp_fu_201_p1;
wire  signed [15:0] grp_fu_204_p0;
wire   [8:0] grp_fu_204_p1;
wire  signed [15:0] grp_fu_205_p0;
wire  signed [10:0] grp_fu_205_p1;
wire  signed [15:0] grp_fu_206_p0;
wire   [6:0] grp_fu_206_p1;
wire  signed [15:0] grp_fu_208_p0;
wire  signed [9:0] grp_fu_208_p1;
wire  signed [15:0] grp_fu_209_p0;
wire   [10:0] grp_fu_209_p1;
wire  signed [15:0] grp_fu_210_p0;
wire  signed [10:0] grp_fu_210_p1;
wire  signed [15:0] grp_fu_211_p0;
wire  signed [8:0] grp_fu_211_p1;
wire  signed [15:0] grp_fu_212_p0;
wire  signed [9:0] grp_fu_212_p1;
wire  signed [15:0] grp_fu_213_p0;
wire   [9:0] grp_fu_213_p1;
wire  signed [15:0] grp_fu_214_p0;
wire   [6:0] grp_fu_214_p1;
wire  signed [15:0] grp_fu_215_p0;
wire  signed [8:0] grp_fu_215_p1;
wire  signed [15:0] grp_fu_216_p0;
wire  signed [9:0] grp_fu_216_p1;
wire  signed [15:0] grp_fu_217_p0;
wire   [8:0] grp_fu_217_p1;
wire  signed [15:0] grp_fu_218_p0;
wire   [8:0] grp_fu_218_p1;
wire  signed [15:0] grp_fu_219_p0;
wire   [8:0] grp_fu_219_p1;
wire  signed [15:0] grp_fu_220_p0;
wire   [9:0] grp_fu_220_p1;
wire  signed [15:0] grp_fu_221_p0;
wire   [9:0] grp_fu_221_p1;
wire  signed [15:0] grp_fu_223_p0;
wire   [8:0] grp_fu_223_p1;
wire  signed [15:0] grp_fu_224_p0;
wire  signed [7:0] grp_fu_224_p1;
wire  signed [15:0] grp_fu_225_p0;
wire   [8:0] grp_fu_225_p1;
wire  signed [15:0] grp_fu_226_p0;
wire   [8:0] grp_fu_226_p1;
wire  signed [15:0] grp_fu_227_p0;
wire   [9:0] grp_fu_227_p1;
wire  signed [15:0] grp_fu_228_p0;
wire   [8:0] grp_fu_228_p1;
wire  signed [15:0] grp_fu_229_p0;
wire  signed [8:0] grp_fu_229_p1;
wire  signed [15:0] sext_ln1118_35_fu_6710_p0;
wire  signed [15:0] sext_ln1118_36_fu_6716_p0;
wire  signed [15:0] sext_ln1118_37_fu_6725_p0;
wire  signed [15:0] sext_ln1118_45_fu_6741_p0;
wire  signed [15:0] sext_ln1118_46_fu_6748_p0;
wire  signed [15:0] sext_ln1118_47_fu_6756_p0;
wire   [17:0] tmp_1_fu_6801_p3;
wire  signed [18:0] sext_ln1118_32_fu_6781_p1;
wire  signed [18:0] sext_ln1118_82_fu_6808_p1;
wire   [18:0] sub_ln1118_16_fu_6812_p2;
wire   [22:0] grp_fu_214_p2;
wire   [23:0] grp_fu_187_p2;
wire   [19:0] shl_ln1118_12_fu_6851_p3;
wire  signed [20:0] sext_ln1118_40_fu_6858_p1;
wire  signed [20:0] sext_ln1118_38_fu_6828_p1;
wire   [20:0] sub_ln1118_1_fu_6862_p2;
wire   [25:0] grp_fu_227_p2;
wire   [25:0] grp_fu_194_p2;
wire   [23:0] shl_ln1118_13_fu_6898_p3;
wire  signed [24:0] sext_ln1118_41_fu_6905_p1;
wire   [17:0] shl_ln1118_14_fu_6915_p3;
wire   [24:0] sub_ln1118_2_fu_6909_p2;
wire  signed [24:0] sext_ln1118_42_fu_6922_p1;
wire   [24:0] sub_ln1118_3_fu_6926_p2;
wire   [25:0] grp_fu_209_p2;
wire   [25:0] grp_fu_196_p2;
wire   [24:0] grp_fu_201_p2;
wire   [22:0] grp_fu_206_p2;
wire   [24:0] grp_fu_183_p2;
wire   [25:0] grp_fu_193_p2;
wire   [25:0] grp_fu_212_p2;
wire   [25:0] grp_fu_190_p2;
wire   [24:0] grp_fu_229_p2;
wire   [25:0] grp_fu_216_p2;
wire   [25:0] grp_fu_186_p2;
wire   [22:0] grp_fu_199_p2;
wire   [23:0] grp_fu_184_p2;
wire   [24:0] grp_fu_223_p2;
wire   [24:0] grp_fu_228_p2;
wire   [23:0] grp_fu_224_p2;
wire   [17:0] tmp_fu_7105_p3;
wire  signed [18:0] sext_ln1118_29_fu_7102_p1;
wire  signed [18:0] sext_ln1118_81_fu_7112_p1;
wire   [18:0] sub_ln1118_15_fu_7116_p2;
wire   [25:0] grp_fu_205_p2;
wire   [21:0] grp_fu_197_p2;
wire   [24:0] grp_fu_218_p2;
wire   [24:0] grp_fu_185_p2;
wire   [24:0] grp_fu_198_p2;
wire   [25:0] grp_fu_182_p2;
wire   [24:0] grp_fu_188_p2;
wire   [23:0] shl_ln_fu_7202_p3;
wire   [18:0] shl_ln1118_11_fu_7213_p3;
wire  signed [24:0] sext_ln1118_31_fu_7220_p1;
wire  signed [24:0] sext_ln1118_30_fu_7209_p1;
wire   [24:0] sub_ln1118_fu_7224_p2;
wire   [24:0] grp_fu_226_p2;
wire   [24:0] grp_fu_215_p2;
wire   [24:0] grp_fu_219_p2;
wire   [25:0] grp_fu_210_p2;
wire   [24:0] grp_fu_204_p2;
wire   [25:0] grp_fu_221_p2;
wire   [24:0] grp_fu_225_p2;
wire   [24:0] grp_fu_217_p2;
wire   [25:0] grp_fu_220_p2;
wire   [24:0] grp_fu_211_p2;
wire   [24:0] grp_fu_200_p2;
wire   [24:0] grp_fu_195_p2;
wire   [25:0] grp_fu_208_p2;
wire   [25:0] grp_fu_213_p2;
wire  signed [20:0] tmp_2_fu_7416_p3;
wire  signed [21:0] sext_ln1118_43_fu_7401_p1;
wire  signed [21:0] sext_ln1118_83_fu_7423_p1;
wire   [21:0] sub_ln1118_17_fu_7427_p2;
wire   [11:0] trunc_ln708_68_fu_7433_p4;
wire   [23:0] shl_ln1118_15_fu_7450_p3;
wire  signed [24:0] sext_ln1118_49_fu_7461_p1;
wire  signed [24:0] sext_ln1118_48_fu_7457_p1;
wire   [24:0] sub_ln1118_4_fu_7465_p2;
wire   [14:0] trunc_ln708_70_fu_7471_p4;
wire  signed [15:0] sext_ln708_21_fu_7380_p1;
wire  signed [15:0] sext_ln708_22_fu_7383_p1;
wire  signed [15:0] sext_ln708_23_fu_7386_p1;
wire  signed [15:0] sext_ln708_28_fu_7404_p1;
wire  signed [15:0] sext_ln708_24_fu_7389_p1;
wire  signed [15:0] sext_ln708_29_fu_7407_p1;
wire  signed [15:0] sext_ln708_30_fu_7410_p1;
wire  signed [15:0] sext_ln708_31_fu_7413_p1;
wire  signed [15:0] sext_ln708_25_fu_7392_p1;
wire  signed [15:0] sext_ln708_32_fu_7443_p1;
wire  signed [15:0] sext_ln708_26_fu_7395_p1;
wire  signed [15:0] sext_ln708_33_fu_7447_p1;
wire  signed [15:0] sext_ln708_27_fu_7398_p1;
wire  signed [15:0] sext_ln708_34_fu_7481_p1;
wire  signed [15:0] sext_ln708_35_fu_7485_p1;
wire  signed [15:0] sext_ln708_fu_7551_p1;
wire   [15:0] add_ln703_fu_7602_p2;
wire  signed [15:0] sext_ln708_14_fu_7581_p1;
wire   [15:0] add_ln703_17_fu_7612_p2;
wire  signed [15:0] sext_ln708_5_fu_7554_p1;
wire   [15:0] add_ln703_20_fu_7622_p2;
wire  signed [15:0] sext_ln708_15_fu_7584_p1;
wire  signed [15:0] sext_ln708_6_fu_7557_p1;
wire   [15:0] add_ln703_23_fu_7632_p2;
wire  signed [15:0] sext_ln708_16_fu_7587_p1;
wire  signed [15:0] sext_ln708_7_fu_7560_p1;
wire   [15:0] add_ln703_26_fu_7643_p2;
wire  signed [15:0] sext_ln708_8_fu_7563_p1;
wire   [15:0] add_ln703_29_fu_7654_p2;
wire  signed [15:0] sext_ln708_17_fu_7590_p1;
wire   [15:0] add_ln703_32_fu_7664_p2;
wire  signed [15:0] sext_ln708_18_fu_7593_p1;
wire  signed [15:0] sext_ln708_9_fu_7566_p1;
wire   [15:0] add_ln703_35_fu_7674_p2;
wire  signed [15:0] sext_ln708_19_fu_7596_p1;
wire  signed [15:0] sext_ln708_10_fu_7569_p1;
wire   [15:0] add_ln703_38_fu_7685_p2;
wire  signed [15:0] sext_ln708_20_fu_7599_p1;
wire  signed [15:0] sext_ln708_11_fu_7572_p1;
wire   [15:0] add_ln703_41_fu_7696_p2;
wire  signed [15:0] sext_ln708_12_fu_7575_p1;
wire   [15:0] add_ln703_44_fu_7707_p2;
wire  signed [15:0] sext_ln708_13_fu_7578_p1;
wire   [15:0] add_ln703_47_fu_7717_p2;
wire   [15:0] add_ln703_122_fu_7607_p2;
wire   [15:0] acc_1_V_fu_7617_p2;
wire   [15:0] acc_2_V_fu_7627_p2;
wire   [15:0] acc_3_V_fu_7638_p2;
wire   [15:0] acc_4_V_fu_7649_p2;
wire   [15:0] acc_5_V_fu_7659_p2;
wire   [15:0] acc_6_V_fu_7669_p2;
wire   [15:0] acc_7_V_fu_7680_p2;
wire   [15:0] acc_8_V_fu_7691_p2;
wire   [15:0] acc_9_V_fu_7702_p2;
wire   [15:0] acc_10_V_fu_7712_p2;
wire   [15:0] acc_11_V_fu_7722_p2;
reg    grp_fu_182_ce;
reg    grp_fu_183_ce;
reg    grp_fu_184_ce;
reg    grp_fu_185_ce;
reg    grp_fu_186_ce;
reg    grp_fu_187_ce;
reg    grp_fu_188_ce;
reg    grp_fu_190_ce;
reg    grp_fu_193_ce;
reg    grp_fu_194_ce;
reg    grp_fu_195_ce;
reg    grp_fu_196_ce;
reg    grp_fu_197_ce;
reg    grp_fu_198_ce;
reg    grp_fu_199_ce;
reg    grp_fu_200_ce;
reg    grp_fu_201_ce;
reg    grp_fu_204_ce;
reg    grp_fu_205_ce;
reg    grp_fu_206_ce;
reg    grp_fu_208_ce;
reg    grp_fu_209_ce;
reg    grp_fu_210_ce;
reg    grp_fu_211_ce;
reg    grp_fu_212_ce;
reg    grp_fu_213_ce;
reg    grp_fu_214_ce;
reg    grp_fu_215_ce;
reg    grp_fu_216_ce;
reg    grp_fu_217_ce;
reg    grp_fu_218_ce;
reg    grp_fu_219_ce;
reg    grp_fu_220_ce;
reg    grp_fu_221_ce;
reg    grp_fu_223_ce;
reg    grp_fu_224_ce;
reg    grp_fu_225_ce;
reg    grp_fu_226_ce;
reg    grp_fu_227_ce;
reg    grp_fu_228_ce;
reg    grp_fu_229_ce;
reg    ap_ce_reg;
reg   [15:0] data_0_V_read_int_reg;
reg   [15:0] data_1_V_read_int_reg;
reg  signed [15:0] data_2_V_read_int_reg;
reg  signed [15:0] data_3_V_read_int_reg;
reg   [15:0] ap_return_0_int_reg;
reg   [15:0] ap_return_1_int_reg;
reg   [15:0] ap_return_2_int_reg;
reg   [15:0] ap_return_3_int_reg;
reg   [15:0] ap_return_4_int_reg;
reg   [15:0] ap_return_5_int_reg;
reg   [15:0] ap_return_6_int_reg;
reg   [15:0] ap_return_7_int_reg;
reg   [15:0] ap_return_8_int_reg;
reg   [15:0] ap_return_9_int_reg;
reg   [15:0] ap_return_10_int_reg;
reg   [15:0] ap_return_11_int_reg;

myproject_mul_16s_11s_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
myproject_mul_16s_11s_26_2_0_U124(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_182_p0),
    .din1(grp_fu_182_p1),
    .ce(grp_fu_182_ce),
    .dout(grp_fu_182_p2)
);

myproject_mul_16s_9s_25_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 25 ))
myproject_mul_16s_9s_25_2_0_U125(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_183_p0),
    .din1(grp_fu_183_p1),
    .ce(grp_fu_183_ce),
    .dout(grp_fu_183_p2)
);

myproject_mul_16s_8s_24_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 24 ))
myproject_mul_16s_8s_24_2_0_U126(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_184_p0),
    .din1(grp_fu_184_p1),
    .ce(grp_fu_184_ce),
    .dout(grp_fu_184_p2)
);

myproject_mul_16s_9s_25_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 25 ))
myproject_mul_16s_9s_25_2_0_U127(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_185_p0),
    .din1(grp_fu_185_p1),
    .ce(grp_fu_185_ce),
    .dout(grp_fu_185_p2)
);

myproject_mul_16s_11s_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
myproject_mul_16s_11s_26_2_0_U128(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_186_p0),
    .din1(grp_fu_186_p1),
    .ce(grp_fu_186_ce),
    .dout(grp_fu_186_p2)
);

myproject_mul_16s_8s_24_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 24 ))
myproject_mul_16s_8s_24_2_0_U129(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(data_2_V_read_int_reg),
    .din1(grp_fu_187_p1),
    .ce(grp_fu_187_ce),
    .dout(grp_fu_187_p2)
);

myproject_mul_16s_9s_25_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 25 ))
myproject_mul_16s_9s_25_2_0_U130(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_188_p0),
    .din1(grp_fu_188_p1),
    .ce(grp_fu_188_ce),
    .dout(grp_fu_188_p2)
);

myproject_mul_16s_10ns_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
myproject_mul_16s_10ns_26_2_0_U131(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_190_p0),
    .din1(grp_fu_190_p1),
    .ce(grp_fu_190_ce),
    .dout(grp_fu_190_p2)
);

myproject_mul_16s_10ns_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
myproject_mul_16s_10ns_26_2_0_U132(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_193_p0),
    .din1(grp_fu_193_p1),
    .ce(grp_fu_193_ce),
    .dout(grp_fu_193_p2)
);

myproject_mul_16s_10s_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
myproject_mul_16s_10s_26_2_0_U133(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_194_p0),
    .din1(grp_fu_194_p1),
    .ce(grp_fu_194_ce),
    .dout(grp_fu_194_p2)
);

myproject_mul_16s_9ns_25_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 25 ))
myproject_mul_16s_9ns_25_2_0_U134(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_195_p0),
    .din1(grp_fu_195_p1),
    .ce(grp_fu_195_ce),
    .dout(grp_fu_195_p2)
);

myproject_mul_16s_10s_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
myproject_mul_16s_10s_26_2_0_U135(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_196_p0),
    .din1(grp_fu_196_p1),
    .ce(grp_fu_196_ce),
    .dout(grp_fu_196_p2)
);

myproject_mul_16s_6s_22_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 22 ))
myproject_mul_16s_6s_22_2_0_U136(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(data_0_V_read_6_reg_7822),
    .din1(grp_fu_197_p1),
    .ce(grp_fu_197_ce),
    .dout(grp_fu_197_p2)
);

myproject_mul_16s_9s_25_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 25 ))
myproject_mul_16s_9s_25_2_0_U137(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_198_p0),
    .din1(grp_fu_198_p1),
    .ce(grp_fu_198_ce),
    .dout(grp_fu_198_p2)
);

myproject_mul_16s_7s_23_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 23 ))
myproject_mul_16s_7s_23_2_0_U138(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(data_3_V_read_int_reg),
    .din1(grp_fu_199_p1),
    .ce(grp_fu_199_ce),
    .dout(grp_fu_199_p2)
);

myproject_mul_16s_9ns_25_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 25 ))
myproject_mul_16s_9ns_25_2_0_U139(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_200_p0),
    .din1(grp_fu_200_p1),
    .ce(grp_fu_200_ce),
    .dout(grp_fu_200_p2)
);

myproject_mul_16s_9ns_25_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 25 ))
myproject_mul_16s_9ns_25_2_0_U140(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_201_p0),
    .din1(grp_fu_201_p1),
    .ce(grp_fu_201_ce),
    .dout(grp_fu_201_p2)
);

myproject_mul_16s_9ns_25_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 25 ))
myproject_mul_16s_9ns_25_2_0_U141(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_204_p0),
    .din1(grp_fu_204_p1),
    .ce(grp_fu_204_ce),
    .dout(grp_fu_204_p2)
);

myproject_mul_16s_11s_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
myproject_mul_16s_11s_26_2_0_U142(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_205_p0),
    .din1(grp_fu_205_p1),
    .ce(grp_fu_205_ce),
    .dout(grp_fu_205_p2)
);

myproject_mul_16s_7ns_23_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 23 ))
myproject_mul_16s_7ns_23_2_0_U143(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_206_p0),
    .din1(grp_fu_206_p1),
    .ce(grp_fu_206_ce),
    .dout(grp_fu_206_p2)
);

myproject_mul_16s_10s_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
myproject_mul_16s_10s_26_2_0_U144(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_208_p0),
    .din1(grp_fu_208_p1),
    .ce(grp_fu_208_ce),
    .dout(grp_fu_208_p2)
);

myproject_mul_16s_11ns_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
myproject_mul_16s_11ns_26_2_0_U145(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_209_p0),
    .din1(grp_fu_209_p1),
    .ce(grp_fu_209_ce),
    .dout(grp_fu_209_p2)
);

myproject_mul_16s_11s_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
myproject_mul_16s_11s_26_2_0_U146(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_210_p0),
    .din1(grp_fu_210_p1),
    .ce(grp_fu_210_ce),
    .dout(grp_fu_210_p2)
);

myproject_mul_16s_9s_25_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 25 ))
myproject_mul_16s_9s_25_2_0_U147(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_211_p0),
    .din1(grp_fu_211_p1),
    .ce(grp_fu_211_ce),
    .dout(grp_fu_211_p2)
);

myproject_mul_16s_10s_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
myproject_mul_16s_10s_26_2_0_U148(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_212_p0),
    .din1(grp_fu_212_p1),
    .ce(grp_fu_212_ce),
    .dout(grp_fu_212_p2)
);

myproject_mul_16s_10ns_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
myproject_mul_16s_10ns_26_2_0_U149(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_213_p0),
    .din1(grp_fu_213_p1),
    .ce(grp_fu_213_ce),
    .dout(grp_fu_213_p2)
);

myproject_mul_16s_7ns_23_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 23 ))
myproject_mul_16s_7ns_23_2_0_U150(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_214_p0),
    .din1(grp_fu_214_p1),
    .ce(grp_fu_214_ce),
    .dout(grp_fu_214_p2)
);

myproject_mul_16s_9s_25_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 25 ))
myproject_mul_16s_9s_25_2_0_U151(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_215_p0),
    .din1(grp_fu_215_p1),
    .ce(grp_fu_215_ce),
    .dout(grp_fu_215_p2)
);

myproject_mul_16s_10s_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
myproject_mul_16s_10s_26_2_0_U152(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_216_p0),
    .din1(grp_fu_216_p1),
    .ce(grp_fu_216_ce),
    .dout(grp_fu_216_p2)
);

myproject_mul_16s_9ns_25_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 25 ))
myproject_mul_16s_9ns_25_2_0_U153(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_217_p0),
    .din1(grp_fu_217_p1),
    .ce(grp_fu_217_ce),
    .dout(grp_fu_217_p2)
);

myproject_mul_16s_9ns_25_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 25 ))
myproject_mul_16s_9ns_25_2_0_U154(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_218_p0),
    .din1(grp_fu_218_p1),
    .ce(grp_fu_218_ce),
    .dout(grp_fu_218_p2)
);

myproject_mul_16s_9ns_25_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 25 ))
myproject_mul_16s_9ns_25_2_0_U155(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_219_p0),
    .din1(grp_fu_219_p1),
    .ce(grp_fu_219_ce),
    .dout(grp_fu_219_p2)
);

myproject_mul_16s_10ns_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
myproject_mul_16s_10ns_26_2_0_U156(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_220_p0),
    .din1(grp_fu_220_p1),
    .ce(grp_fu_220_ce),
    .dout(grp_fu_220_p2)
);

myproject_mul_16s_10ns_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
myproject_mul_16s_10ns_26_2_0_U157(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_221_p0),
    .din1(grp_fu_221_p1),
    .ce(grp_fu_221_ce),
    .dout(grp_fu_221_p2)
);

myproject_mul_16s_9ns_25_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 25 ))
myproject_mul_16s_9ns_25_2_0_U158(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_223_p0),
    .din1(grp_fu_223_p1),
    .ce(grp_fu_223_ce),
    .dout(grp_fu_223_p2)
);

myproject_mul_16s_8s_24_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 24 ))
myproject_mul_16s_8s_24_2_0_U159(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_224_p0),
    .din1(grp_fu_224_p1),
    .ce(grp_fu_224_ce),
    .dout(grp_fu_224_p2)
);

myproject_mul_16s_9ns_25_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 25 ))
myproject_mul_16s_9ns_25_2_0_U160(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_225_p0),
    .din1(grp_fu_225_p1),
    .ce(grp_fu_225_ce),
    .dout(grp_fu_225_p2)
);

myproject_mul_16s_9ns_25_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 25 ))
myproject_mul_16s_9ns_25_2_0_U161(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_226_p0),
    .din1(grp_fu_226_p1),
    .ce(grp_fu_226_ce),
    .dout(grp_fu_226_p2)
);

myproject_mul_16s_10ns_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
myproject_mul_16s_10ns_26_2_0_U162(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_227_p0),
    .din1(grp_fu_227_p1),
    .ce(grp_fu_227_ce),
    .dout(grp_fu_227_p2)
);

myproject_mul_16s_9ns_25_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 25 ))
myproject_mul_16s_9ns_25_2_0_U163(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_228_p0),
    .din1(grp_fu_228_p1),
    .ce(grp_fu_228_ce),
    .dout(grp_fu_228_p2)
);

myproject_mul_16s_9s_25_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 25 ))
myproject_mul_16s_9s_25_2_0_U164(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_229_p0),
    .din1(grp_fu_229_p1),
    .ce(grp_fu_229_ce),
    .dout(grp_fu_229_p2)
);

always @ (posedge ap_clk) begin
    ap_ce_reg <= ap_ce;
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        add_ln703_15_reg_8156 <= add_ln703_15_fu_7488_p2;
        add_ln703_18_reg_8161 <= add_ln703_18_fu_7493_p2;
        add_ln703_21_reg_8166 <= add_ln703_21_fu_7498_p2;
        add_ln703_24_reg_8171 <= add_ln703_24_fu_7504_p2;
        add_ln703_27_reg_8176 <= add_ln703_27_fu_7508_p2;
        add_ln703_30_reg_8181 <= add_ln703_30_fu_7512_p2;
        add_ln703_33_reg_8186 <= add_ln703_33_fu_7518_p2;
        add_ln703_36_reg_8191 <= add_ln703_36_fu_7523_p2;
        add_ln703_39_reg_8196 <= add_ln703_39_fu_7528_p2;
        add_ln703_42_reg_8201 <= add_ln703_42_fu_7534_p2;
        add_ln703_45_reg_8206 <= add_ln703_45_fu_7540_p2;
        add_ln703_48_reg_8211 <= add_ln703_48_fu_7546_p2;
        data_0_V_read_6_reg_7822 <= data_0_V_read_int_reg;
        data_0_V_read_6_reg_7822_pp0_iter1_reg <= data_0_V_read_6_reg_7822;
        data_1_V_read_6_reg_7814 <= data_1_V_read_int_reg;
        data_2_V_read_6_reg_7806 <= data_2_V_read_int_reg;
        data_3_V_read_6_reg_7799 <= data_3_V_read_int_reg;
        data_3_V_read_6_reg_7799_pp0_iter1_reg <= data_3_V_read_6_reg_7799;
        trunc_ln708_25_reg_8046 <= {{grp_fu_205_p2[25:10]}};
        trunc_ln708_26_reg_8051 <= {{grp_fu_197_p2[21:10]}};
        trunc_ln708_27_reg_8056 <= {{grp_fu_218_p2[24:10]}};
        trunc_ln708_28_reg_8061 <= {{grp_fu_185_p2[24:10]}};
        trunc_ln708_29_reg_8066 <= {{grp_fu_198_p2[24:10]}};
        trunc_ln708_30_reg_8071 <= {{grp_fu_182_p2[25:10]}};
        trunc_ln708_31_reg_8076 <= {{grp_fu_188_p2[24:10]}};
        trunc_ln708_32_reg_8081 <= {{sub_ln1118_fu_7224_p2[24:10]}};
        trunc_ln708_33_reg_8086 <= {{grp_fu_226_p2[24:10]}};
        trunc_ln708_34_reg_8091 <= {{grp_fu_215_p2[24:10]}};
        trunc_ln708_35_reg_8096 <= {{grp_fu_219_p2[24:10]}};
        trunc_ln708_36_reg_8101 <= {{grp_fu_210_p2[25:10]}};
        trunc_ln708_37_reg_8106 <= {{grp_fu_204_p2[24:10]}};
        trunc_ln708_38_reg_8111 <= {{grp_fu_221_p2[25:10]}};
        trunc_ln708_39_reg_8116 <= {{grp_fu_225_p2[24:10]}};
        trunc_ln708_40_reg_8121 <= {{grp_fu_217_p2[24:10]}};
        trunc_ln708_41_reg_8126 <= {{grp_fu_220_p2[25:10]}};
        trunc_ln708_42_reg_8131 <= {{grp_fu_211_p2[24:10]}};
        trunc_ln708_43_reg_8136 <= {{grp_fu_200_p2[24:10]}};
        trunc_ln708_44_reg_8141 <= {{grp_fu_195_p2[24:10]}};
        trunc_ln708_45_reg_7926 <= {{sub_ln1118_16_fu_6812_p2[18:10]}};
        trunc_ln708_45_reg_7926_pp0_iter2_reg <= trunc_ln708_45_reg_7926;
        trunc_ln708_46_reg_8146 <= {{grp_fu_208_p2[25:10]}};
        trunc_ln708_47_reg_8151 <= {{grp_fu_213_p2[25:10]}};
        trunc_ln708_48_reg_7931 <= {{grp_fu_214_p2[22:10]}};
        trunc_ln708_49_reg_7936 <= {{grp_fu_187_p2[23:10]}};
        trunc_ln708_50_reg_7941 <= {{sub_ln1118_1_fu_6862_p2[20:10]}};
        trunc_ln708_51_reg_7946 <= {{grp_fu_227_p2[25:10]}};
        trunc_ln708_52_reg_7951 <= {{grp_fu_194_p2[25:10]}};
        trunc_ln708_53_reg_7956 <= {{sub_ln1118_3_fu_6926_p2[24:10]}};
        trunc_ln708_54_reg_7961 <= {{grp_fu_209_p2[25:10]}};
        trunc_ln708_55_reg_7966 <= {{grp_fu_196_p2[25:10]}};
        trunc_ln708_56_reg_7971 <= {{grp_fu_201_p2[24:10]}};
        trunc_ln708_57_reg_7976 <= {{grp_fu_206_p2[22:10]}};
        trunc_ln708_58_reg_7981 <= {{grp_fu_183_p2[24:10]}};
        trunc_ln708_59_reg_7986 <= {{grp_fu_193_p2[25:10]}};
        trunc_ln708_60_reg_7991 <= {{grp_fu_212_p2[25:10]}};
        trunc_ln708_61_reg_7996 <= {{grp_fu_190_p2[25:10]}};
        trunc_ln708_62_reg_8001 <= {{grp_fu_229_p2[24:10]}};
        trunc_ln708_63_reg_8006 <= {{grp_fu_216_p2[25:10]}};
        trunc_ln708_64_reg_8011 <= {{grp_fu_186_p2[25:10]}};
        trunc_ln708_65_reg_8016 <= {{grp_fu_199_p2[22:10]}};
        trunc_ln708_66_reg_8021 <= {{grp_fu_184_p2[23:10]}};
        trunc_ln708_67_reg_8026 <= {{grp_fu_223_p2[24:10]}};
        trunc_ln708_69_reg_8031 <= {{grp_fu_228_p2[24:10]}};
        trunc_ln708_71_reg_8036 <= {{grp_fu_224_p2[23:10]}};
        trunc_ln_reg_8041 <= {{sub_ln1118_15_fu_7116_p2[18:10]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce_reg)) begin
        ap_return_0_int_reg <= add_ln703_122_fu_7607_p2;
        ap_return_10_int_reg <= acc_10_V_fu_7712_p2;
        ap_return_11_int_reg <= acc_11_V_fu_7722_p2;
        ap_return_1_int_reg <= acc_1_V_fu_7617_p2;
        ap_return_2_int_reg <= acc_2_V_fu_7627_p2;
        ap_return_3_int_reg <= acc_3_V_fu_7638_p2;
        ap_return_4_int_reg <= acc_4_V_fu_7649_p2;
        ap_return_5_int_reg <= acc_5_V_fu_7659_p2;
        ap_return_6_int_reg <= acc_6_V_fu_7669_p2;
        ap_return_7_int_reg <= acc_7_V_fu_7680_p2;
        ap_return_8_int_reg <= acc_8_V_fu_7691_p2;
        ap_return_9_int_reg <= acc_9_V_fu_7702_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce)) begin
        data_0_V_read_int_reg <= data_0_V_read;
        data_1_V_read_int_reg <= data_1_V_read;
        data_2_V_read_int_reg <= data_2_V_read;
        data_3_V_read_int_reg <= data_3_V_read;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_0 = ap_return_0_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_0 = add_ln703_122_fu_7607_p2;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_1 = ap_return_1_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_1 = acc_1_V_fu_7617_p2;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_10 = ap_return_10_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_10 = acc_10_V_fu_7712_p2;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_11 = ap_return_11_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_11 = acc_11_V_fu_7722_p2;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_2 = ap_return_2_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_2 = acc_2_V_fu_7627_p2;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_3 = ap_return_3_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_3 = acc_3_V_fu_7638_p2;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_4 = ap_return_4_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_4 = acc_4_V_fu_7649_p2;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_5 = ap_return_5_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_5 = acc_5_V_fu_7659_p2;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_6 = ap_return_6_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_6 = acc_6_V_fu_7669_p2;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_7 = ap_return_7_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_7 = acc_7_V_fu_7680_p2;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_8 = ap_return_8_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_8 = acc_8_V_fu_7691_p2;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_9 = ap_return_9_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_9 = acc_9_V_fu_7702_p2;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_182_ce = 1'b1;
    end else begin
        grp_fu_182_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_183_ce = 1'b1;
    end else begin
        grp_fu_183_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_184_ce = 1'b1;
    end else begin
        grp_fu_184_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_185_ce = 1'b1;
    end else begin
        grp_fu_185_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_186_ce = 1'b1;
    end else begin
        grp_fu_186_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_187_ce = 1'b1;
    end else begin
        grp_fu_187_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_188_ce = 1'b1;
    end else begin
        grp_fu_188_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_190_ce = 1'b1;
    end else begin
        grp_fu_190_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_193_ce = 1'b1;
    end else begin
        grp_fu_193_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_194_ce = 1'b1;
    end else begin
        grp_fu_194_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_195_ce = 1'b1;
    end else begin
        grp_fu_195_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_196_ce = 1'b1;
    end else begin
        grp_fu_196_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_197_ce = 1'b1;
    end else begin
        grp_fu_197_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_198_ce = 1'b1;
    end else begin
        grp_fu_198_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_199_ce = 1'b1;
    end else begin
        grp_fu_199_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_200_ce = 1'b1;
    end else begin
        grp_fu_200_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_201_ce = 1'b1;
    end else begin
        grp_fu_201_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_204_ce = 1'b1;
    end else begin
        grp_fu_204_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_205_ce = 1'b1;
    end else begin
        grp_fu_205_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_206_ce = 1'b1;
    end else begin
        grp_fu_206_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_208_ce = 1'b1;
    end else begin
        grp_fu_208_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_209_ce = 1'b1;
    end else begin
        grp_fu_209_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_210_ce = 1'b1;
    end else begin
        grp_fu_210_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_211_ce = 1'b1;
    end else begin
        grp_fu_211_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_212_ce = 1'b1;
    end else begin
        grp_fu_212_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_213_ce = 1'b1;
    end else begin
        grp_fu_213_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_214_ce = 1'b1;
    end else begin
        grp_fu_214_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_215_ce = 1'b1;
    end else begin
        grp_fu_215_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_216_ce = 1'b1;
    end else begin
        grp_fu_216_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_217_ce = 1'b1;
    end else begin
        grp_fu_217_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_218_ce = 1'b1;
    end else begin
        grp_fu_218_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_219_ce = 1'b1;
    end else begin
        grp_fu_219_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_220_ce = 1'b1;
    end else begin
        grp_fu_220_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_221_ce = 1'b1;
    end else begin
        grp_fu_221_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_223_ce = 1'b1;
    end else begin
        grp_fu_223_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_224_ce = 1'b1;
    end else begin
        grp_fu_224_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_225_ce = 1'b1;
    end else begin
        grp_fu_225_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_226_ce = 1'b1;
    end else begin
        grp_fu_226_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_227_ce = 1'b1;
    end else begin
        grp_fu_227_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_228_ce = 1'b1;
    end else begin
        grp_fu_228_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_229_ce = 1'b1;
    end else begin
        grp_fu_229_ce = 1'b0;
    end
end

assign acc_10_V_fu_7712_p2 = (add_ln703_45_reg_8206 + add_ln703_44_fu_7707_p2);

assign acc_11_V_fu_7722_p2 = (add_ln703_48_reg_8211 + add_ln703_47_fu_7717_p2);

assign acc_1_V_fu_7617_p2 = (add_ln703_18_reg_8161 + add_ln703_17_fu_7612_p2);

assign acc_2_V_fu_7627_p2 = (add_ln703_21_reg_8166 + add_ln703_20_fu_7622_p2);

assign acc_3_V_fu_7638_p2 = (add_ln703_24_reg_8171 + add_ln703_23_fu_7632_p2);

assign acc_4_V_fu_7649_p2 = (add_ln703_27_reg_8176 + add_ln703_26_fu_7643_p2);

assign acc_5_V_fu_7659_p2 = (add_ln703_30_reg_8181 + add_ln703_29_fu_7654_p2);

assign acc_6_V_fu_7669_p2 = (add_ln703_33_reg_8186 + add_ln703_32_fu_7664_p2);

assign acc_7_V_fu_7680_p2 = (add_ln703_36_reg_8191 + add_ln703_35_fu_7674_p2);

assign acc_8_V_fu_7691_p2 = (add_ln703_39_reg_8196 + add_ln703_38_fu_7685_p2);

assign acc_9_V_fu_7702_p2 = (add_ln703_42_reg_8201 + add_ln703_41_fu_7696_p2);

assign add_ln703_122_fu_7607_p2 = (add_ln703_15_reg_8156 + add_ln703_fu_7602_p2);

assign add_ln703_15_fu_7488_p2 = ($signed(sext_ln708_21_fu_7380_p1) + $signed(trunc_ln708_60_reg_7991));

assign add_ln703_17_fu_7612_p2 = ($signed(sext_ln708_14_fu_7581_p1) + $signed(trunc_ln708_25_reg_8046));

assign add_ln703_18_fu_7493_p2 = ($signed(sext_ln708_22_fu_7383_p1) + $signed(trunc_ln708_61_reg_7996));

assign add_ln703_20_fu_7622_p2 = ($signed(trunc_ln708_38_reg_8111) + $signed(sext_ln708_5_fu_7554_p1));

assign add_ln703_21_fu_7498_p2 = ($signed(sext_ln708_23_fu_7386_p1) + $signed(sext_ln708_28_fu_7404_p1));

assign add_ln703_23_fu_7632_p2 = ($signed(sext_ln708_15_fu_7584_p1) + $signed(sext_ln708_6_fu_7557_p1));

assign add_ln703_24_fu_7504_p2 = (trunc_ln708_51_reg_7946 + trunc_ln708_63_reg_8006);

assign add_ln703_26_fu_7643_p2 = ($signed(sext_ln708_16_fu_7587_p1) + $signed(sext_ln708_7_fu_7560_p1));

assign add_ln703_27_fu_7508_p2 = (trunc_ln708_52_reg_7951 + trunc_ln708_64_reg_8011);

assign add_ln703_29_fu_7654_p2 = ($signed(trunc_ln708_41_reg_8126) + $signed(sext_ln708_8_fu_7563_p1));

assign add_ln703_30_fu_7512_p2 = ($signed(sext_ln708_24_fu_7389_p1) + $signed(sext_ln708_29_fu_7407_p1));

assign add_ln703_32_fu_7664_p2 = ($signed(sext_ln708_17_fu_7590_p1) + $signed(trunc_ln708_30_reg_8071));

assign add_ln703_33_fu_7518_p2 = ($signed(trunc_ln708_54_reg_7961) + $signed(sext_ln708_30_fu_7410_p1));

assign add_ln703_35_fu_7674_p2 = ($signed(sext_ln708_18_fu_7593_p1) + $signed(sext_ln708_9_fu_7566_p1));

assign add_ln703_36_fu_7523_p2 = ($signed(trunc_ln708_55_reg_7966) + $signed(sext_ln708_31_fu_7413_p1));

assign add_ln703_38_fu_7685_p2 = ($signed(sext_ln708_19_fu_7596_p1) + $signed(sext_ln708_10_fu_7569_p1));

assign add_ln703_39_fu_7528_p2 = ($signed(sext_ln708_25_fu_7392_p1) + $signed(sext_ln708_32_fu_7443_p1));

assign add_ln703_41_fu_7696_p2 = ($signed(sext_ln708_20_fu_7599_p1) + $signed(sext_ln708_11_fu_7572_p1));

assign add_ln703_42_fu_7534_p2 = ($signed(sext_ln708_26_fu_7395_p1) + $signed(sext_ln708_33_fu_7447_p1));

assign add_ln703_44_fu_7707_p2 = ($signed(trunc_ln708_46_reg_8146) + $signed(sext_ln708_12_fu_7575_p1));

assign add_ln703_45_fu_7540_p2 = ($signed(sext_ln708_27_fu_7398_p1) + $signed(sext_ln708_34_fu_7481_p1));

assign add_ln703_47_fu_7717_p2 = ($signed(trunc_ln708_47_reg_8151) + $signed(sext_ln708_13_fu_7578_p1));

assign add_ln703_48_fu_7546_p2 = ($signed(trunc_ln708_59_reg_7986) + $signed(sext_ln708_35_fu_7485_p1));

assign add_ln703_fu_7602_p2 = ($signed(trunc_ln708_36_reg_8101) + $signed(sext_ln708_fu_7551_p1));

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign grp_fu_182_p0 = sext_ln1118_28_fu_6776_p1;

assign grp_fu_182_p1 = 26'd67108254;

assign grp_fu_183_p0 = sext_ln1118_35_fu_6710_p1;

assign grp_fu_183_p1 = 25'd33554212;

assign grp_fu_184_p0 = sext_ln1118_47_fu_6756_p1;

assign grp_fu_184_p1 = 24'd16777133;

assign grp_fu_185_p0 = sext_ln1118_fu_6762_p1;

assign grp_fu_185_p1 = 25'd33554225;

assign grp_fu_186_p0 = sext_ln1118_46_fu_6748_p1;

assign grp_fu_186_p1 = 26'd67108085;

assign grp_fu_187_p1 = 24'd16777097;

assign grp_fu_188_p0 = sext_ln1118_fu_6762_p1;

assign grp_fu_188_p1 = 25'd33554219;

assign grp_fu_190_p0 = sext_ln1118_46_fu_6748_p1;

assign grp_fu_190_p1 = 26'd332;

assign grp_fu_193_p0 = sext_ln1118_36_fu_6716_p1;

assign grp_fu_193_p1 = 26'd452;

assign grp_fu_194_p0 = sext_ln1118_36_fu_6716_p1;

assign grp_fu_194_p1 = 26'd67108572;

assign grp_fu_195_p0 = sext_ln1118_33_fu_6784_p1;

assign grp_fu_195_p1 = 25'd183;

assign grp_fu_196_p0 = sext_ln1118_36_fu_6716_p1;

assign grp_fu_196_p1 = 26'd67108563;

assign grp_fu_197_p1 = 22'd4194277;

assign grp_fu_198_p0 = sext_ln1118_fu_6762_p1;

assign grp_fu_198_p1 = 25'd33554274;

assign grp_fu_199_p1 = 23'd8388550;

assign grp_fu_200_p0 = sext_ln1118_33_fu_6784_p1;

assign grp_fu_200_p1 = 25'd131;

assign grp_fu_201_p0 = sext_ln1118_35_fu_6710_p1;

assign grp_fu_201_p1 = 25'd194;

assign grp_fu_204_p0 = sext_ln1118_33_fu_6784_p1;

assign grp_fu_204_p1 = 25'd239;

assign grp_fu_205_p0 = sext_ln1118_28_fu_6776_p1;

assign grp_fu_205_p1 = 26'd67108301;

assign grp_fu_206_p0 = sext_ln1118_37_fu_6725_p1;

assign grp_fu_206_p1 = 23'd51;

assign grp_fu_208_p0 = sext_ln1118_34_fu_6793_p1;

assign grp_fu_208_p1 = 26'd67108591;

assign grp_fu_209_p0 = sext_ln1118_36_fu_6716_p1;

assign grp_fu_209_p1 = 26'd649;

assign grp_fu_210_p0 = sext_ln1118_34_fu_6793_p1;

assign grp_fu_210_p1 = 26'd67108267;

assign grp_fu_211_p0 = sext_ln1118_33_fu_6784_p1;

assign grp_fu_211_p1 = 25'd33554248;

assign grp_fu_212_p0 = sext_ln1118_46_fu_6748_p1;

assign grp_fu_212_p1 = 26'd67108569;

assign grp_fu_213_p0 = sext_ln1118_34_fu_6793_p1;

assign grp_fu_213_p1 = 26'd451;

assign grp_fu_214_p0 = sext_ln1118_37_fu_6725_p1;

assign grp_fu_214_p1 = 23'd52;

assign grp_fu_215_p0 = sext_ln1118_fu_6762_p1;

assign grp_fu_215_p1 = 25'd33554250;

assign grp_fu_216_p0 = sext_ln1118_46_fu_6748_p1;

assign grp_fu_216_p1 = 26'd67108595;

assign grp_fu_217_p0 = sext_ln1118_33_fu_6784_p1;

assign grp_fu_217_p1 = 25'd242;

assign grp_fu_218_p0 = sext_ln1118_fu_6762_p1;

assign grp_fu_218_p1 = 25'd219;

assign grp_fu_219_p0 = sext_ln1118_fu_6762_p1;

assign grp_fu_219_p1 = 25'd225;

assign grp_fu_220_p0 = sext_ln1118_34_fu_6793_p1;

assign grp_fu_220_p1 = 26'd280;

assign grp_fu_221_p0 = sext_ln1118_34_fu_6793_p1;

assign grp_fu_221_p1 = 26'd301;

assign grp_fu_223_p0 = sext_ln1118_45_fu_6741_p1;

assign grp_fu_223_p1 = 25'd215;

assign grp_fu_224_p0 = sext_ln1118_47_fu_6756_p1;

assign grp_fu_224_p1 = 24'd16777115;

assign grp_fu_225_p0 = sext_ln1118_33_fu_6784_p1;

assign grp_fu_225_p1 = 25'd209;

assign grp_fu_226_p0 = sext_ln1118_fu_6762_p1;

assign grp_fu_226_p1 = 25'd231;

assign grp_fu_227_p0 = sext_ln1118_36_fu_6716_p1;

assign grp_fu_227_p1 = 26'd271;

assign grp_fu_228_p0 = sext_ln1118_45_fu_6741_p1;

assign grp_fu_228_p1 = 25'd178;

assign grp_fu_229_p0 = sext_ln1118_45_fu_6741_p1;

assign grp_fu_229_p1 = 25'd33554274;

assign sext_ln1118_28_fu_6776_p1 = data_0_V_read_6_reg_7822;

assign sext_ln1118_29_fu_7102_p1 = data_0_V_read_6_reg_7822_pp0_iter1_reg;

assign sext_ln1118_30_fu_7209_p1 = $signed(shl_ln_fu_7202_p3);

assign sext_ln1118_31_fu_7220_p1 = $signed(shl_ln1118_11_fu_7213_p3);

assign sext_ln1118_32_fu_6781_p1 = data_1_V_read_6_reg_7814;

assign sext_ln1118_33_fu_6784_p1 = data_1_V_read_6_reg_7814;

assign sext_ln1118_34_fu_6793_p1 = data_1_V_read_6_reg_7814;

assign sext_ln1118_35_fu_6710_p0 = data_2_V_read_int_reg;

assign sext_ln1118_35_fu_6710_p1 = sext_ln1118_35_fu_6710_p0;

assign sext_ln1118_36_fu_6716_p0 = data_2_V_read_int_reg;

assign sext_ln1118_36_fu_6716_p1 = sext_ln1118_36_fu_6716_p0;

assign sext_ln1118_37_fu_6725_p0 = data_2_V_read_int_reg;

assign sext_ln1118_37_fu_6725_p1 = sext_ln1118_37_fu_6725_p0;

assign sext_ln1118_38_fu_6828_p1 = data_2_V_read_6_reg_7806;

assign sext_ln1118_40_fu_6858_p1 = $signed(shl_ln1118_12_fu_6851_p3);

assign sext_ln1118_41_fu_6905_p1 = $signed(shl_ln1118_13_fu_6898_p3);

assign sext_ln1118_42_fu_6922_p1 = $signed(shl_ln1118_14_fu_6915_p3);

assign sext_ln1118_43_fu_7401_p1 = data_3_V_read_6_reg_7799_pp0_iter1_reg;

assign sext_ln1118_45_fu_6741_p0 = data_3_V_read_int_reg;

assign sext_ln1118_45_fu_6741_p1 = sext_ln1118_45_fu_6741_p0;

assign sext_ln1118_46_fu_6748_p0 = data_3_V_read_int_reg;

assign sext_ln1118_46_fu_6748_p1 = sext_ln1118_46_fu_6748_p0;

assign sext_ln1118_47_fu_6756_p0 = data_3_V_read_int_reg;

assign sext_ln1118_47_fu_6756_p1 = sext_ln1118_47_fu_6756_p0;

assign sext_ln1118_48_fu_7457_p1 = $signed(shl_ln1118_15_fu_7450_p3);

assign sext_ln1118_49_fu_7461_p1 = tmp_2_fu_7416_p3;

assign sext_ln1118_81_fu_7112_p1 = $signed(tmp_fu_7105_p3);

assign sext_ln1118_82_fu_6808_p1 = $signed(tmp_1_fu_6801_p3);

assign sext_ln1118_83_fu_7423_p1 = tmp_2_fu_7416_p3;

assign sext_ln1118_fu_6762_p1 = data_0_V_read_6_reg_7822;

assign sext_ln708_10_fu_7569_p1 = $signed(trunc_ln708_32_reg_8081);

assign sext_ln708_11_fu_7572_p1 = $signed(trunc_ln708_33_reg_8086);

assign sext_ln708_12_fu_7575_p1 = $signed(trunc_ln708_34_reg_8091);

assign sext_ln708_13_fu_7578_p1 = $signed(trunc_ln708_35_reg_8096);

assign sext_ln708_14_fu_7581_p1 = $signed(trunc_ln708_37_reg_8106);

assign sext_ln708_15_fu_7584_p1 = $signed(trunc_ln708_39_reg_8116);

assign sext_ln708_16_fu_7587_p1 = $signed(trunc_ln708_40_reg_8121);

assign sext_ln708_17_fu_7590_p1 = $signed(trunc_ln708_42_reg_8131);

assign sext_ln708_18_fu_7593_p1 = $signed(trunc_ln708_43_reg_8136);

assign sext_ln708_19_fu_7596_p1 = $signed(trunc_ln708_44_reg_8141);

assign sext_ln708_20_fu_7599_p1 = $signed(trunc_ln708_45_reg_7926_pp0_iter2_reg);

assign sext_ln708_21_fu_7380_p1 = $signed(trunc_ln708_48_reg_7931);

assign sext_ln708_22_fu_7383_p1 = $signed(trunc_ln708_49_reg_7936);

assign sext_ln708_23_fu_7386_p1 = $signed(trunc_ln708_50_reg_7941);

assign sext_ln708_24_fu_7389_p1 = $signed(trunc_ln708_53_reg_7956);

assign sext_ln708_25_fu_7392_p1 = $signed(trunc_ln708_56_reg_7971);

assign sext_ln708_26_fu_7395_p1 = $signed(trunc_ln708_57_reg_7976);

assign sext_ln708_27_fu_7398_p1 = $signed(trunc_ln708_58_reg_7981);

assign sext_ln708_28_fu_7404_p1 = $signed(trunc_ln708_62_reg_8001);

assign sext_ln708_29_fu_7407_p1 = $signed(trunc_ln708_65_reg_8016);

assign sext_ln708_30_fu_7410_p1 = $signed(trunc_ln708_66_reg_8021);

assign sext_ln708_31_fu_7413_p1 = $signed(trunc_ln708_67_reg_8026);

assign sext_ln708_32_fu_7443_p1 = $signed(trunc_ln708_68_fu_7433_p4);

assign sext_ln708_33_fu_7447_p1 = $signed(trunc_ln708_69_reg_8031);

assign sext_ln708_34_fu_7481_p1 = $signed(trunc_ln708_70_fu_7471_p4);

assign sext_ln708_35_fu_7485_p1 = $signed(trunc_ln708_71_reg_8036);

assign sext_ln708_5_fu_7554_p1 = $signed(trunc_ln708_26_reg_8051);

assign sext_ln708_6_fu_7557_p1 = $signed(trunc_ln708_27_reg_8056);

assign sext_ln708_7_fu_7560_p1 = $signed(trunc_ln708_28_reg_8061);

assign sext_ln708_8_fu_7563_p1 = $signed(trunc_ln708_29_reg_8066);

assign sext_ln708_9_fu_7566_p1 = $signed(trunc_ln708_31_reg_8076);

assign sext_ln708_fu_7551_p1 = $signed(trunc_ln_reg_8041);

assign shl_ln1118_11_fu_7213_p3 = {{data_0_V_read_6_reg_7822_pp0_iter1_reg}, {3'd0}};

assign shl_ln1118_12_fu_6851_p3 = {{data_2_V_read_6_reg_7806}, {4'd0}};

assign shl_ln1118_13_fu_6898_p3 = {{data_2_V_read_6_reg_7806}, {8'd0}};

assign shl_ln1118_14_fu_6915_p3 = {{data_2_V_read_6_reg_7806}, {2'd0}};

assign shl_ln1118_15_fu_7450_p3 = {{data_3_V_read_6_reg_7799_pp0_iter1_reg}, {8'd0}};

assign shl_ln_fu_7202_p3 = {{data_0_V_read_6_reg_7822_pp0_iter1_reg}, {8'd0}};

assign sub_ln1118_15_fu_7116_p2 = ($signed(sext_ln1118_29_fu_7102_p1) - $signed(sext_ln1118_81_fu_7112_p1));

assign sub_ln1118_16_fu_6812_p2 = ($signed(sext_ln1118_32_fu_6781_p1) - $signed(sext_ln1118_82_fu_6808_p1));

assign sub_ln1118_17_fu_7427_p2 = ($signed(sext_ln1118_43_fu_7401_p1) - $signed(sext_ln1118_83_fu_7423_p1));

assign sub_ln1118_1_fu_6862_p2 = ($signed(sext_ln1118_40_fu_6858_p1) - $signed(sext_ln1118_38_fu_6828_p1));

assign sub_ln1118_2_fu_6909_p2 = ($signed(25'd0) - $signed(sext_ln1118_41_fu_6905_p1));

assign sub_ln1118_3_fu_6926_p2 = ($signed(sub_ln1118_2_fu_6909_p2) - $signed(sext_ln1118_42_fu_6922_p1));

assign sub_ln1118_4_fu_7465_p2 = ($signed(sext_ln1118_49_fu_7461_p1) - $signed(sext_ln1118_48_fu_7457_p1));

assign sub_ln1118_fu_7224_p2 = ($signed(sext_ln1118_31_fu_7220_p1) - $signed(sext_ln1118_30_fu_7209_p1));

assign tmp_1_fu_6801_p3 = {{data_1_V_read_6_reg_7814}, {2'd0}};

assign tmp_2_fu_7416_p3 = {{data_3_V_read_6_reg_7799_pp0_iter1_reg}, {5'd0}};

assign tmp_fu_7105_p3 = {{data_0_V_read_6_reg_7822_pp0_iter1_reg}, {2'd0}};

assign trunc_ln708_68_fu_7433_p4 = {{sub_ln1118_17_fu_7427_p2[21:10]}};

assign trunc_ln708_70_fu_7471_p4 = {{sub_ln1118_4_fu_7465_p2[24:10]}};

endmodule //dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0
