// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "myproject.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic myproject::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic myproject::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<105> myproject::ap_ST_fsm_state1 = "1";
const sc_lv<105> myproject::ap_ST_fsm_state2 = "10";
const sc_lv<105> myproject::ap_ST_fsm_state3 = "100";
const sc_lv<105> myproject::ap_ST_fsm_state4 = "1000";
const sc_lv<105> myproject::ap_ST_fsm_state5 = "10000";
const sc_lv<105> myproject::ap_ST_fsm_state6 = "100000";
const sc_lv<105> myproject::ap_ST_fsm_state7 = "1000000";
const sc_lv<105> myproject::ap_ST_fsm_state8 = "10000000";
const sc_lv<105> myproject::ap_ST_fsm_state9 = "100000000";
const sc_lv<105> myproject::ap_ST_fsm_state10 = "1000000000";
const sc_lv<105> myproject::ap_ST_fsm_state11 = "10000000000";
const sc_lv<105> myproject::ap_ST_fsm_state12 = "100000000000";
const sc_lv<105> myproject::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<105> myproject::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<105> myproject::ap_ST_fsm_state15 = "100000000000000";
const sc_lv<105> myproject::ap_ST_fsm_state16 = "1000000000000000";
const sc_lv<105> myproject::ap_ST_fsm_state17 = "10000000000000000";
const sc_lv<105> myproject::ap_ST_fsm_state18 = "100000000000000000";
const sc_lv<105> myproject::ap_ST_fsm_state19 = "1000000000000000000";
const sc_lv<105> myproject::ap_ST_fsm_state20 = "10000000000000000000";
const sc_lv<105> myproject::ap_ST_fsm_state21 = "100000000000000000000";
const sc_lv<105> myproject::ap_ST_fsm_state22 = "1000000000000000000000";
const sc_lv<105> myproject::ap_ST_fsm_state23 = "10000000000000000000000";
const sc_lv<105> myproject::ap_ST_fsm_state24 = "100000000000000000000000";
const sc_lv<105> myproject::ap_ST_fsm_state25 = "1000000000000000000000000";
const sc_lv<105> myproject::ap_ST_fsm_state26 = "10000000000000000000000000";
const sc_lv<105> myproject::ap_ST_fsm_state27 = "100000000000000000000000000";
const sc_lv<105> myproject::ap_ST_fsm_state28 = "1000000000000000000000000000";
const sc_lv<105> myproject::ap_ST_fsm_state29 = "10000000000000000000000000000";
const sc_lv<105> myproject::ap_ST_fsm_state30 = "100000000000000000000000000000";
const sc_lv<105> myproject::ap_ST_fsm_state31 = "1000000000000000000000000000000";
const sc_lv<105> myproject::ap_ST_fsm_state32 = "10000000000000000000000000000000";
const sc_lv<105> myproject::ap_ST_fsm_state33 = "100000000000000000000000000000000";
const sc_lv<105> myproject::ap_ST_fsm_state34 = "1000000000000000000000000000000000";
const sc_lv<105> myproject::ap_ST_fsm_state35 = "10000000000000000000000000000000000";
const sc_lv<105> myproject::ap_ST_fsm_state36 = "100000000000000000000000000000000000";
const sc_lv<105> myproject::ap_ST_fsm_state37 = "1000000000000000000000000000000000000";
const sc_lv<105> myproject::ap_ST_fsm_state38 = "10000000000000000000000000000000000000";
const sc_lv<105> myproject::ap_ST_fsm_state39 = "100000000000000000000000000000000000000";
const sc_lv<105> myproject::ap_ST_fsm_state40 = "1000000000000000000000000000000000000000";
const sc_lv<105> myproject::ap_ST_fsm_state41 = "10000000000000000000000000000000000000000";
const sc_lv<105> myproject::ap_ST_fsm_state42 = "100000000000000000000000000000000000000000";
const sc_lv<105> myproject::ap_ST_fsm_state43 = "1000000000000000000000000000000000000000000";
const sc_lv<105> myproject::ap_ST_fsm_state44 = "10000000000000000000000000000000000000000000";
const sc_lv<105> myproject::ap_ST_fsm_state45 = "100000000000000000000000000000000000000000000";
const sc_lv<105> myproject::ap_ST_fsm_state46 = "1000000000000000000000000000000000000000000000";
const sc_lv<105> myproject::ap_ST_fsm_state47 = "10000000000000000000000000000000000000000000000";
const sc_lv<105> myproject::ap_ST_fsm_state48 = "100000000000000000000000000000000000000000000000";
const sc_lv<105> myproject::ap_ST_fsm_state49 = "1000000000000000000000000000000000000000000000000";
const sc_lv<105> myproject::ap_ST_fsm_state50 = "10000000000000000000000000000000000000000000000000";
const sc_lv<105> myproject::ap_ST_fsm_state51 = "100000000000000000000000000000000000000000000000000";
const sc_lv<105> myproject::ap_ST_fsm_state52 = "1000000000000000000000000000000000000000000000000000";
const sc_lv<105> myproject::ap_ST_fsm_state53 = "10000000000000000000000000000000000000000000000000000";
const sc_lv<105> myproject::ap_ST_fsm_state54 = "100000000000000000000000000000000000000000000000000000";
const sc_lv<105> myproject::ap_ST_fsm_state55 = "1000000000000000000000000000000000000000000000000000000";
const sc_lv<105> myproject::ap_ST_fsm_state56 = "10000000000000000000000000000000000000000000000000000000";
const sc_lv<105> myproject::ap_ST_fsm_state57 = "100000000000000000000000000000000000000000000000000000000";
const sc_lv<105> myproject::ap_ST_fsm_state58 = "1000000000000000000000000000000000000000000000000000000000";
const sc_lv<105> myproject::ap_ST_fsm_state59 = "10000000000000000000000000000000000000000000000000000000000";
const sc_lv<105> myproject::ap_ST_fsm_state60 = "100000000000000000000000000000000000000000000000000000000000";
const sc_lv<105> myproject::ap_ST_fsm_state61 = "1000000000000000000000000000000000000000000000000000000000000";
const sc_lv<105> myproject::ap_ST_fsm_state62 = "10000000000000000000000000000000000000000000000000000000000000";
const sc_lv<105> myproject::ap_ST_fsm_state63 = "100000000000000000000000000000000000000000000000000000000000000";
const sc_lv<105> myproject::ap_ST_fsm_state64 = "1000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<105> myproject::ap_ST_fsm_state65 = "10000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<105> myproject::ap_ST_fsm_state66 = "100000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<105> myproject::ap_ST_fsm_state67 = "1000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<105> myproject::ap_ST_fsm_state68 = "10000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<105> myproject::ap_ST_fsm_state69 = "100000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<105> myproject::ap_ST_fsm_state70 = "1000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<105> myproject::ap_ST_fsm_state71 = "10000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<105> myproject::ap_ST_fsm_state72 = "100000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<105> myproject::ap_ST_fsm_state73 = "1000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<105> myproject::ap_ST_fsm_state74 = "10000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<105> myproject::ap_ST_fsm_state75 = "100000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<105> myproject::ap_ST_fsm_state76 = "1000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<105> myproject::ap_ST_fsm_state77 = "10000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<105> myproject::ap_ST_fsm_state78 = "100000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<105> myproject::ap_ST_fsm_state79 = "1000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<105> myproject::ap_ST_fsm_state80 = "10000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<105> myproject::ap_ST_fsm_state81 = "100000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<105> myproject::ap_ST_fsm_state82 = "1000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<105> myproject::ap_ST_fsm_state83 = "10000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<105> myproject::ap_ST_fsm_state84 = "100000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<105> myproject::ap_ST_fsm_state85 = "1000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<105> myproject::ap_ST_fsm_state86 = "10000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<105> myproject::ap_ST_fsm_state87 = "100000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<105> myproject::ap_ST_fsm_state88 = "1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<105> myproject::ap_ST_fsm_state89 = "10000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<105> myproject::ap_ST_fsm_state90 = "100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<105> myproject::ap_ST_fsm_state91 = "1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<105> myproject::ap_ST_fsm_state92 = "10000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<105> myproject::ap_ST_fsm_state93 = "100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<105> myproject::ap_ST_fsm_state94 = "1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<105> myproject::ap_ST_fsm_state95 = "10000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<105> myproject::ap_ST_fsm_state96 = "100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<105> myproject::ap_ST_fsm_state97 = "1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<105> myproject::ap_ST_fsm_state98 = "10000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<105> myproject::ap_ST_fsm_state99 = "100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<105> myproject::ap_ST_fsm_state100 = "1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<105> myproject::ap_ST_fsm_state101 = "10000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<105> myproject::ap_ST_fsm_state102 = "100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<105> myproject::ap_ST_fsm_state103 = "1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<105> myproject::ap_ST_fsm_state104 = "10000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<105> myproject::ap_ST_fsm_state105 = "100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<32> myproject::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<800> myproject::ap_const_lv800_lc_1 = "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<32> myproject::ap_const_lv32_14 = "10100";
const sc_lv<32> myproject::ap_const_lv32_10 = "10000";
const sc_lv<32> myproject::ap_const_lv32_15 = "10101";
const sc_lv<32> myproject::ap_const_lv32_1F = "11111";
const sc_lv<32> myproject::ap_const_lv32_20 = "100000";
const sc_lv<32> myproject::ap_const_lv32_29 = "101001";
const sc_lv<32> myproject::ap_const_lv32_2A = "101010";
const sc_lv<32> myproject::ap_const_lv32_2F = "101111";
const sc_lv<32> myproject::ap_const_lv32_30 = "110000";
const sc_lv<32> myproject::ap_const_lv32_3E = "111110";
const sc_lv<32> myproject::ap_const_lv32_3F = "111111";
const sc_lv<32> myproject::ap_const_lv32_40 = "1000000";
const sc_lv<32> myproject::ap_const_lv32_4F = "1001111";
const sc_lv<32> myproject::ap_const_lv32_50 = "1010000";
const sc_lv<32> myproject::ap_const_lv32_53 = "1010011";
const sc_lv<32> myproject::ap_const_lv32_54 = "1010100";
const sc_lv<32> myproject::ap_const_lv32_5F = "1011111";
const sc_lv<32> myproject::ap_const_lv32_60 = "1100000";
const sc_lv<32> myproject::ap_const_lv32_67 = "1100111";
const sc_lv<32> myproject::ap_const_lv32_68 = "1101000";
const sc_lv<1> myproject::ap_const_lv1_1 = "1";
const sc_lv<1> myproject::ap_const_lv1_0 = "0";
const sc_lv<32> myproject::ap_const_lv32_6F = "1101111";
const sc_lv<32> myproject::ap_const_lv32_70 = "1110000";
const sc_lv<32> myproject::ap_const_lv32_7F = "1111111";
const sc_lv<32> myproject::ap_const_lv32_80 = "10000000";
const sc_lv<32> myproject::ap_const_lv32_8F = "10001111";
const sc_lv<32> myproject::ap_const_lv32_90 = "10010000";
const sc_lv<32> myproject::ap_const_lv32_9F = "10011111";
const sc_lv<32> myproject::ap_const_lv32_A0 = "10100000";
const sc_lv<32> myproject::ap_const_lv32_AF = "10101111";
const sc_lv<32> myproject::ap_const_lv32_B0 = "10110000";
const sc_lv<32> myproject::ap_const_lv32_BF = "10111111";
const sc_lv<32> myproject::ap_const_lv32_C0 = "11000000";
const sc_lv<32> myproject::ap_const_lv32_CF = "11001111";
const sc_lv<32> myproject::ap_const_lv32_D0 = "11010000";
const sc_lv<32> myproject::ap_const_lv32_DF = "11011111";
const sc_lv<32> myproject::ap_const_lv32_E0 = "11100000";
const sc_lv<32> myproject::ap_const_lv32_EF = "11101111";
const sc_lv<32> myproject::ap_const_lv32_F0 = "11110000";
const sc_lv<32> myproject::ap_const_lv32_FF = "11111111";
const sc_lv<32> myproject::ap_const_lv32_100 = "100000000";
const sc_lv<32> myproject::ap_const_lv32_10F = "100001111";
const sc_lv<32> myproject::ap_const_lv32_110 = "100010000";
const sc_lv<32> myproject::ap_const_lv32_11F = "100011111";
const sc_lv<32> myproject::ap_const_lv32_120 = "100100000";
const sc_lv<32> myproject::ap_const_lv32_12F = "100101111";
const sc_lv<32> myproject::ap_const_lv32_130 = "100110000";
const sc_lv<32> myproject::ap_const_lv32_13F = "100111111";
const sc_lv<32> myproject::ap_const_lv32_140 = "101000000";
const sc_lv<32> myproject::ap_const_lv32_14F = "101001111";
const sc_lv<32> myproject::ap_const_lv32_150 = "101010000";
const sc_lv<32> myproject::ap_const_lv32_15F = "101011111";
const sc_lv<32> myproject::ap_const_lv32_160 = "101100000";
const sc_lv<32> myproject::ap_const_lv32_16F = "101101111";
const sc_lv<32> myproject::ap_const_lv32_170 = "101110000";
const sc_lv<32> myproject::ap_const_lv32_17F = "101111111";
const sc_lv<32> myproject::ap_const_lv32_180 = "110000000";
const sc_lv<32> myproject::ap_const_lv32_18F = "110001111";
const sc_lv<32> myproject::ap_const_lv32_190 = "110010000";
const sc_lv<32> myproject::ap_const_lv32_19F = "110011111";
const sc_lv<32> myproject::ap_const_lv32_1A0 = "110100000";
const sc_lv<32> myproject::ap_const_lv32_1AF = "110101111";
const sc_lv<32> myproject::ap_const_lv32_1B0 = "110110000";
const sc_lv<32> myproject::ap_const_lv32_1BF = "110111111";
const sc_lv<32> myproject::ap_const_lv32_1C0 = "111000000";
const sc_lv<32> myproject::ap_const_lv32_1CF = "111001111";
const sc_lv<32> myproject::ap_const_lv32_1D0 = "111010000";
const sc_lv<32> myproject::ap_const_lv32_1DF = "111011111";
const sc_lv<32> myproject::ap_const_lv32_1E0 = "111100000";
const sc_lv<32> myproject::ap_const_lv32_1EF = "111101111";
const sc_lv<32> myproject::ap_const_lv32_1F0 = "111110000";
const sc_lv<32> myproject::ap_const_lv32_1FF = "111111111";
const sc_lv<32> myproject::ap_const_lv32_200 = "1000000000";
const sc_lv<32> myproject::ap_const_lv32_20F = "1000001111";
const sc_lv<32> myproject::ap_const_lv32_210 = "1000010000";
const sc_lv<32> myproject::ap_const_lv32_21F = "1000011111";
const sc_lv<32> myproject::ap_const_lv32_220 = "1000100000";
const sc_lv<32> myproject::ap_const_lv32_22F = "1000101111";
const sc_lv<32> myproject::ap_const_lv32_230 = "1000110000";
const sc_lv<32> myproject::ap_const_lv32_23F = "1000111111";
const sc_lv<32> myproject::ap_const_lv32_240 = "1001000000";
const sc_lv<32> myproject::ap_const_lv32_24F = "1001001111";
const sc_lv<32> myproject::ap_const_lv32_250 = "1001010000";
const sc_lv<32> myproject::ap_const_lv32_25F = "1001011111";
const sc_lv<32> myproject::ap_const_lv32_260 = "1001100000";
const sc_lv<32> myproject::ap_const_lv32_26F = "1001101111";
const sc_lv<32> myproject::ap_const_lv32_270 = "1001110000";
const sc_lv<32> myproject::ap_const_lv32_27F = "1001111111";
const sc_lv<32> myproject::ap_const_lv32_280 = "1010000000";
const sc_lv<32> myproject::ap_const_lv32_28F = "1010001111";
const sc_lv<32> myproject::ap_const_lv32_290 = "1010010000";
const sc_lv<32> myproject::ap_const_lv32_29F = "1010011111";
const sc_lv<32> myproject::ap_const_lv32_2A0 = "1010100000";
const sc_lv<32> myproject::ap_const_lv32_2AF = "1010101111";
const sc_lv<32> myproject::ap_const_lv32_2B0 = "1010110000";
const sc_lv<32> myproject::ap_const_lv32_2BF = "1010111111";
const sc_lv<32> myproject::ap_const_lv32_2C0 = "1011000000";
const sc_lv<32> myproject::ap_const_lv32_2CF = "1011001111";
const sc_lv<32> myproject::ap_const_lv32_2D0 = "1011010000";
const sc_lv<32> myproject::ap_const_lv32_2DF = "1011011111";
const sc_lv<32> myproject::ap_const_lv32_2E0 = "1011100000";
const sc_lv<32> myproject::ap_const_lv32_2EF = "1011101111";
const sc_lv<32> myproject::ap_const_lv32_2F0 = "1011110000";
const sc_lv<32> myproject::ap_const_lv32_2FF = "1011111111";
const sc_lv<32> myproject::ap_const_lv32_300 = "1100000000";
const sc_lv<32> myproject::ap_const_lv32_30F = "1100001111";
const sc_lv<32> myproject::ap_const_lv32_310 = "1100010000";
const sc_lv<32> myproject::ap_const_lv32_31F = "1100011111";
const bool myproject::ap_const_boolean_1 = true;

myproject::myproject(sc_module_name name) : sc_module(name), mVcdFile(0) {
    grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261 = new gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s("grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261");
    grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261->ap_clk(ap_clk);
    grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261->ap_rst(ap_rst);
    grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261->ap_start(grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_ap_start);
    grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261->ap_done(grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_ap_done);
    grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261->ap_idle(grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_ap_idle);
    grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261->ap_ready(grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_ap_ready);
    grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261->ap_ce(grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_ap_ce);
    grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261->reset_state(grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_reset_state);
    grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261->data_0_V_read(grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_0_V_read);
    grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261->data_1_V_read(grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_1_V_read);
    grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261->data_2_V_read(grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_2_V_read);
    grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261->data_3_V_read(grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_3_V_read);
    grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261->data_4_V_read(grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_4_V_read);
    grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261->data_5_V_read(grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_5_V_read);
    grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261->data_6_V_read(grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_6_V_read);
    grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261->data_7_V_read(grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_7_V_read);
    grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261->data_8_V_read(grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_8_V_read);
    grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261->data_9_V_read(grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_9_V_read);
    grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261->ap_return(grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_ap_return);
    grp_dense_latency_ap_fixed_ap_fixed_config3_0_0_fu_284 = new dense_latency_ap_fixed_ap_fixed_config3_0_0("grp_dense_latency_ap_fixed_ap_fixed_config3_0_0_fu_284");
    grp_dense_latency_ap_fixed_ap_fixed_config3_0_0_fu_284->ap_clk(ap_clk);
    grp_dense_latency_ap_fixed_ap_fixed_config3_0_0_fu_284->ap_rst(ap_rst);
    grp_dense_latency_ap_fixed_ap_fixed_config3_0_0_fu_284->data_0_V_read(h_state_0_V_reg_994);
    grp_dense_latency_ap_fixed_ap_fixed_config3_0_0_fu_284->ap_return(grp_dense_latency_ap_fixed_ap_fixed_config3_0_0_fu_284_ap_return);
    grp_dense_latency_ap_fixed_ap_fixed_config3_0_0_fu_284->ap_ce(grp_dense_latency_ap_fixed_ap_fixed_config3_0_0_fu_284_ap_ce);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state104);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state105);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state21);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state22);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state42);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state43);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state63);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state64);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state84);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state85);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_NS_fsm_state22);
    sensitive << ( ap_NS_fsm );

    SC_METHOD(thread_ap_NS_fsm_state43);
    sensitive << ( ap_NS_fsm );

    SC_METHOD(thread_ap_NS_fsm_state64);
    sensitive << ( ap_NS_fsm );

    SC_METHOD(thread_ap_NS_fsm_state85);
    sensitive << ( ap_NS_fsm );

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( ap_start );
    sensitive << ( input_1_V_ap_vld_in_sig );

    SC_METHOD(thread_ap_block_state1_ignore_call21);
    sensitive << ( ap_start );
    sensitive << ( input_1_V_ap_vld_in_sig );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_CS_fsm_state105 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state105 );

    SC_METHOD(thread_data_in_0_V_fu_290_p1);
    sensitive << ( input_1_V_in_sig );

    SC_METHOD(thread_grp_dense_latency_ap_fixed_ap_fixed_config3_0_0_fu_284_ap_ce);
    sensitive << ( ap_CS_fsm_state104 );
    sensitive << ( ap_CS_fsm_state105 );

    SC_METHOD(thread_grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_ap_ce);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( input_1_V_ap_vld_in_sig );

    SC_METHOD(thread_grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_ap_start);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( input_1_V_ap_vld_in_sig );
    sensitive << ( grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_ap_start_reg );

    SC_METHOD(thread_grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_0_V_read);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_in_0_V_1_reg_794 );
    sensitive << ( data_in_0_V_2_reg_844 );
    sensitive << ( data_in_0_V_3_reg_894 );
    sensitive << ( data_in_0_V_4_reg_944 );
    sensitive << ( ap_CS_fsm_state22 );
    sensitive << ( ap_CS_fsm_state43 );
    sensitive << ( ap_CS_fsm_state64 );
    sensitive << ( ap_CS_fsm_state85 );
    sensitive << ( data_in_0_V_fu_290_p1 );

    SC_METHOD(thread_grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_1_V_read);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( input_1_V_in_sig );
    sensitive << ( data_in_1_V_1_reg_799 );
    sensitive << ( data_in_1_V_2_reg_849 );
    sensitive << ( data_in_1_V_3_reg_899 );
    sensitive << ( data_in_1_V_4_reg_949 );
    sensitive << ( ap_CS_fsm_state22 );
    sensitive << ( ap_CS_fsm_state43 );
    sensitive << ( ap_CS_fsm_state64 );
    sensitive << ( ap_CS_fsm_state85 );

    SC_METHOD(thread_grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_2_V_read);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( input_1_V_in_sig );
    sensitive << ( data_in_2_V_1_reg_804 );
    sensitive << ( data_in_2_V_2_reg_854 );
    sensitive << ( data_in_2_V_3_reg_904 );
    sensitive << ( data_in_2_V_4_reg_954 );
    sensitive << ( ap_CS_fsm_state22 );
    sensitive << ( ap_CS_fsm_state43 );
    sensitive << ( ap_CS_fsm_state64 );
    sensitive << ( ap_CS_fsm_state85 );

    SC_METHOD(thread_grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_3_V_read);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( input_1_V_in_sig );
    sensitive << ( data_in_3_V_1_reg_809 );
    sensitive << ( data_in_3_V_2_reg_859 );
    sensitive << ( data_in_3_V_3_reg_909 );
    sensitive << ( data_in_3_V_4_reg_959 );
    sensitive << ( ap_CS_fsm_state22 );
    sensitive << ( ap_CS_fsm_state43 );
    sensitive << ( ap_CS_fsm_state64 );
    sensitive << ( ap_CS_fsm_state85 );

    SC_METHOD(thread_grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_4_V_read);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( input_1_V_in_sig );
    sensitive << ( data_in_4_V_1_reg_814 );
    sensitive << ( data_in_4_V_2_reg_864 );
    sensitive << ( data_in_4_V_3_reg_914 );
    sensitive << ( data_in_4_V_4_reg_964 );
    sensitive << ( ap_CS_fsm_state22 );
    sensitive << ( ap_CS_fsm_state43 );
    sensitive << ( ap_CS_fsm_state64 );
    sensitive << ( ap_CS_fsm_state85 );

    SC_METHOD(thread_grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_5_V_read);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( input_1_V_in_sig );
    sensitive << ( data_in_5_V_1_reg_819 );
    sensitive << ( data_in_5_V_2_reg_869 );
    sensitive << ( data_in_5_V_3_reg_919 );
    sensitive << ( data_in_5_V_4_reg_969 );
    sensitive << ( ap_CS_fsm_state22 );
    sensitive << ( ap_CS_fsm_state43 );
    sensitive << ( ap_CS_fsm_state64 );
    sensitive << ( ap_CS_fsm_state85 );

    SC_METHOD(thread_grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_6_V_read);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( input_1_V_in_sig );
    sensitive << ( data_in_6_V_1_reg_824 );
    sensitive << ( data_in_6_V_2_reg_874 );
    sensitive << ( data_in_6_V_3_reg_924 );
    sensitive << ( data_in_6_V_4_reg_974 );
    sensitive << ( ap_CS_fsm_state22 );
    sensitive << ( ap_CS_fsm_state43 );
    sensitive << ( ap_CS_fsm_state64 );
    sensitive << ( ap_CS_fsm_state85 );

    SC_METHOD(thread_grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_7_V_read);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( input_1_V_in_sig );
    sensitive << ( data_in_7_V_1_reg_829 );
    sensitive << ( data_in_7_V_2_reg_879 );
    sensitive << ( data_in_7_V_3_reg_929 );
    sensitive << ( data_in_7_V_4_reg_979 );
    sensitive << ( ap_CS_fsm_state22 );
    sensitive << ( ap_CS_fsm_state43 );
    sensitive << ( ap_CS_fsm_state64 );
    sensitive << ( ap_CS_fsm_state85 );

    SC_METHOD(thread_grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_8_V_read);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( input_1_V_in_sig );
    sensitive << ( data_in_8_V_1_reg_834 );
    sensitive << ( data_in_8_V_2_reg_884 );
    sensitive << ( data_in_8_V_3_reg_934 );
    sensitive << ( data_in_8_V_4_reg_984 );
    sensitive << ( ap_CS_fsm_state22 );
    sensitive << ( ap_CS_fsm_state43 );
    sensitive << ( ap_CS_fsm_state64 );
    sensitive << ( ap_CS_fsm_state85 );

    SC_METHOD(thread_grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_9_V_read);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( input_1_V_in_sig );
    sensitive << ( data_in_9_V_1_reg_839 );
    sensitive << ( data_in_9_V_2_reg_889 );
    sensitive << ( data_in_9_V_3_reg_939 );
    sensitive << ( data_in_9_V_4_reg_989 );
    sensitive << ( ap_CS_fsm_state22 );
    sensitive << ( ap_CS_fsm_state43 );
    sensitive << ( ap_CS_fsm_state64 );
    sensitive << ( ap_CS_fsm_state85 );

    SC_METHOD(thread_grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_reset_state);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state22 );
    sensitive << ( ap_CS_fsm_state43 );
    sensitive << ( ap_CS_fsm_state64 );
    sensitive << ( ap_CS_fsm_state85 );

    SC_METHOD(thread_input_1_V_ap_vld_in_sig);
    sensitive << ( input_1_V_ap_vld );
    sensitive << ( input_1_V_ap_vld_preg );

    SC_METHOD(thread_input_1_V_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( input_1_V_ap_vld );

    SC_METHOD(thread_input_1_V_in_sig);
    sensitive << ( input_1_V );
    sensitive << ( input_1_V_preg );
    sensitive << ( input_1_V_ap_vld );

    SC_METHOD(thread_layer3_out_0_V);
    sensitive << ( ap_CS_fsm_state105 );
    sensitive << ( grp_dense_latency_ap_fixed_ap_fixed_config3_0_0_fu_284_ap_return );

    SC_METHOD(thread_layer3_out_0_V_ap_vld);
    sensitive << ( ap_CS_fsm_state105 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( input_1_V_ap_vld_in_sig );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    ap_CS_fsm = "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001";
    input_1_V_preg = "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    input_1_V_ap_vld_preg = SC_LOGIC_0;
    grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_ap_start_reg = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "myproject_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, input_1_V, "(port)input_1_V");
    sc_trace(mVcdFile, input_1_V_ap_vld, "(port)input_1_V_ap_vld");
    sc_trace(mVcdFile, layer3_out_0_V, "(port)layer3_out_0_V");
    sc_trace(mVcdFile, layer3_out_0_V_ap_vld, "(port)layer3_out_0_V_ap_vld");
    sc_trace(mVcdFile, layer3_out_1_V, "(port)layer3_out_1_V");
    sc_trace(mVcdFile, layer3_out_1_V_ap_vld, "(port)layer3_out_1_V_ap_vld");
    sc_trace(mVcdFile, layer3_out_2_V, "(port)layer3_out_2_V");
    sc_trace(mVcdFile, layer3_out_2_V_ap_vld, "(port)layer3_out_2_V_ap_vld");
    sc_trace(mVcdFile, layer3_out_3_V, "(port)layer3_out_3_V");
    sc_trace(mVcdFile, layer3_out_3_V_ap_vld, "(port)layer3_out_3_V_ap_vld");
    sc_trace(mVcdFile, layer3_out_4_V, "(port)layer3_out_4_V");
    sc_trace(mVcdFile, layer3_out_4_V_ap_vld, "(port)layer3_out_4_V_ap_vld");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, input_1_V_preg, "input_1_V_preg");
    sc_trace(mVcdFile, input_1_V_in_sig, "input_1_V_in_sig");
    sc_trace(mVcdFile, input_1_V_ap_vld_preg, "input_1_V_ap_vld_preg");
    sc_trace(mVcdFile, input_1_V_ap_vld_in_sig, "input_1_V_ap_vld_in_sig");
    sc_trace(mVcdFile, input_1_V_blk_n, "input_1_V_blk_n");
    sc_trace(mVcdFile, data_in_0_V_1_reg_794, "data_in_0_V_1_reg_794");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, data_in_1_V_1_reg_799, "data_in_1_V_1_reg_799");
    sc_trace(mVcdFile, data_in_2_V_1_reg_804, "data_in_2_V_1_reg_804");
    sc_trace(mVcdFile, data_in_3_V_1_reg_809, "data_in_3_V_1_reg_809");
    sc_trace(mVcdFile, data_in_4_V_1_reg_814, "data_in_4_V_1_reg_814");
    sc_trace(mVcdFile, data_in_5_V_1_reg_819, "data_in_5_V_1_reg_819");
    sc_trace(mVcdFile, data_in_6_V_1_reg_824, "data_in_6_V_1_reg_824");
    sc_trace(mVcdFile, data_in_7_V_1_reg_829, "data_in_7_V_1_reg_829");
    sc_trace(mVcdFile, data_in_8_V_1_reg_834, "data_in_8_V_1_reg_834");
    sc_trace(mVcdFile, data_in_9_V_1_reg_839, "data_in_9_V_1_reg_839");
    sc_trace(mVcdFile, data_in_0_V_2_reg_844, "data_in_0_V_2_reg_844");
    sc_trace(mVcdFile, data_in_1_V_2_reg_849, "data_in_1_V_2_reg_849");
    sc_trace(mVcdFile, data_in_2_V_2_reg_854, "data_in_2_V_2_reg_854");
    sc_trace(mVcdFile, data_in_3_V_2_reg_859, "data_in_3_V_2_reg_859");
    sc_trace(mVcdFile, data_in_4_V_2_reg_864, "data_in_4_V_2_reg_864");
    sc_trace(mVcdFile, data_in_5_V_2_reg_869, "data_in_5_V_2_reg_869");
    sc_trace(mVcdFile, data_in_6_V_2_reg_874, "data_in_6_V_2_reg_874");
    sc_trace(mVcdFile, data_in_7_V_2_reg_879, "data_in_7_V_2_reg_879");
    sc_trace(mVcdFile, data_in_8_V_2_reg_884, "data_in_8_V_2_reg_884");
    sc_trace(mVcdFile, data_in_9_V_2_reg_889, "data_in_9_V_2_reg_889");
    sc_trace(mVcdFile, data_in_0_V_3_reg_894, "data_in_0_V_3_reg_894");
    sc_trace(mVcdFile, data_in_1_V_3_reg_899, "data_in_1_V_3_reg_899");
    sc_trace(mVcdFile, data_in_2_V_3_reg_904, "data_in_2_V_3_reg_904");
    sc_trace(mVcdFile, data_in_3_V_3_reg_909, "data_in_3_V_3_reg_909");
    sc_trace(mVcdFile, data_in_4_V_3_reg_914, "data_in_4_V_3_reg_914");
    sc_trace(mVcdFile, data_in_5_V_3_reg_919, "data_in_5_V_3_reg_919");
    sc_trace(mVcdFile, data_in_6_V_3_reg_924, "data_in_6_V_3_reg_924");
    sc_trace(mVcdFile, data_in_7_V_3_reg_929, "data_in_7_V_3_reg_929");
    sc_trace(mVcdFile, data_in_8_V_3_reg_934, "data_in_8_V_3_reg_934");
    sc_trace(mVcdFile, data_in_9_V_3_reg_939, "data_in_9_V_3_reg_939");
    sc_trace(mVcdFile, data_in_0_V_4_reg_944, "data_in_0_V_4_reg_944");
    sc_trace(mVcdFile, data_in_1_V_4_reg_949, "data_in_1_V_4_reg_949");
    sc_trace(mVcdFile, data_in_2_V_4_reg_954, "data_in_2_V_4_reg_954");
    sc_trace(mVcdFile, data_in_3_V_4_reg_959, "data_in_3_V_4_reg_959");
    sc_trace(mVcdFile, data_in_4_V_4_reg_964, "data_in_4_V_4_reg_964");
    sc_trace(mVcdFile, data_in_5_V_4_reg_969, "data_in_5_V_4_reg_969");
    sc_trace(mVcdFile, data_in_6_V_4_reg_974, "data_in_6_V_4_reg_974");
    sc_trace(mVcdFile, data_in_7_V_4_reg_979, "data_in_7_V_4_reg_979");
    sc_trace(mVcdFile, data_in_8_V_4_reg_984, "data_in_8_V_4_reg_984");
    sc_trace(mVcdFile, data_in_9_V_4_reg_989, "data_in_9_V_4_reg_989");
    sc_trace(mVcdFile, grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_ap_return, "grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_ap_return");
    sc_trace(mVcdFile, h_state_0_V_reg_994, "h_state_0_V_reg_994");
    sc_trace(mVcdFile, ap_CS_fsm_state21, "ap_CS_fsm_state21");
    sc_trace(mVcdFile, grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_ap_start, "grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_ap_start");
    sc_trace(mVcdFile, grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_ap_done, "grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_ap_done");
    sc_trace(mVcdFile, grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_ap_idle, "grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_ap_idle");
    sc_trace(mVcdFile, grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_ap_ready, "grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_ap_ready");
    sc_trace(mVcdFile, grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_ap_ce, "grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_ap_ce");
    sc_trace(mVcdFile, grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_reset_state, "grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_reset_state");
    sc_trace(mVcdFile, grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_0_V_read, "grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_0_V_read");
    sc_trace(mVcdFile, grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_1_V_read, "grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_1_V_read");
    sc_trace(mVcdFile, grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_2_V_read, "grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_2_V_read");
    sc_trace(mVcdFile, grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_3_V_read, "grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_3_V_read");
    sc_trace(mVcdFile, grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_4_V_read, "grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_4_V_read");
    sc_trace(mVcdFile, grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_5_V_read, "grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_5_V_read");
    sc_trace(mVcdFile, grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_6_V_read, "grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_6_V_read");
    sc_trace(mVcdFile, grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_7_V_read, "grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_7_V_read");
    sc_trace(mVcdFile, grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_8_V_read, "grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_8_V_read");
    sc_trace(mVcdFile, grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_9_V_read, "grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_9_V_read");
    sc_trace(mVcdFile, ap_block_state1_ignore_call21, "ap_block_state1_ignore_call21");
    sc_trace(mVcdFile, ap_CS_fsm_state22, "ap_CS_fsm_state22");
    sc_trace(mVcdFile, ap_CS_fsm_state42, "ap_CS_fsm_state42");
    sc_trace(mVcdFile, ap_CS_fsm_state43, "ap_CS_fsm_state43");
    sc_trace(mVcdFile, ap_CS_fsm_state63, "ap_CS_fsm_state63");
    sc_trace(mVcdFile, ap_CS_fsm_state64, "ap_CS_fsm_state64");
    sc_trace(mVcdFile, ap_CS_fsm_state84, "ap_CS_fsm_state84");
    sc_trace(mVcdFile, ap_CS_fsm_state85, "ap_CS_fsm_state85");
    sc_trace(mVcdFile, ap_CS_fsm_state104, "ap_CS_fsm_state104");
    sc_trace(mVcdFile, ap_CS_fsm_state105, "ap_CS_fsm_state105");
    sc_trace(mVcdFile, grp_dense_latency_ap_fixed_ap_fixed_config3_0_0_fu_284_ap_return, "grp_dense_latency_ap_fixed_ap_fixed_config3_0_0_fu_284_ap_return");
    sc_trace(mVcdFile, grp_dense_latency_ap_fixed_ap_fixed_config3_0_0_fu_284_ap_ce, "grp_dense_latency_ap_fixed_ap_fixed_config3_0_0_fu_284_ap_ce");
    sc_trace(mVcdFile, grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_ap_start_reg, "grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_ap_start_reg");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_NS_fsm_state22, "ap_NS_fsm_state22");
    sc_trace(mVcdFile, ap_NS_fsm_state43, "ap_NS_fsm_state43");
    sc_trace(mVcdFile, ap_NS_fsm_state64, "ap_NS_fsm_state64");
    sc_trace(mVcdFile, ap_NS_fsm_state85, "ap_NS_fsm_state85");
    sc_trace(mVcdFile, data_in_0_V_fu_290_p1, "data_in_0_V_fu_290_p1");
#endif

    }
    mHdltvinHandle.open("myproject.hdltvin.dat");
    mHdltvoutHandle.open("myproject.hdltvout.dat");
}

myproject::~myproject() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261;
    delete grp_dense_latency_ap_fixed_ap_fixed_config3_0_0_fu_284;
}

void myproject::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_ap_start_reg = ap_const_logic_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read()) && 
              esl_seteq<1,1,1>(ap_const_logic_1, ap_NS_fsm_state22.read())) || 
             (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state42.read()) && 
              esl_seteq<1,1,1>(ap_const_logic_1, ap_NS_fsm_state43.read())) || 
             (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state63.read()) && 
              esl_seteq<1,1,1>(ap_const_logic_1, ap_NS_fsm_state64.read())) || 
             (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state84.read()) && 
              esl_seteq<1,1,1>(ap_const_logic_1, ap_NS_fsm_state85.read())))) {
            grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_ap_ready.read())) {
            grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_ap_start_reg = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        input_1_V_ap_vld_preg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state105.read())) {
            input_1_V_ap_vld_preg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, input_1_V_ap_vld.read()) && 
                    !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())))) {
            input_1_V_ap_vld_preg = input_1_V_ap_vld.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        input_1_V_preg = ap_const_lv800_lc_1;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, input_1_V_ap_vld.read()) && 
             !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())))) {
            input_1_V_preg = input_1_V.read();
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_const_logic_0, input_1_V_ap_vld_in_sig.read())))) {
        data_in_0_V_1_reg_794 = input_1_V_in_sig.read().range(175, 160);
        data_in_0_V_2_reg_844 = input_1_V_in_sig.read().range(335, 320);
        data_in_0_V_3_reg_894 = input_1_V_in_sig.read().range(495, 480);
        data_in_0_V_4_reg_944 = input_1_V_in_sig.read().range(655, 640);
        data_in_1_V_1_reg_799 = input_1_V_in_sig.read().range(191, 176);
        data_in_1_V_2_reg_849 = input_1_V_in_sig.read().range(351, 336);
        data_in_1_V_3_reg_899 = input_1_V_in_sig.read().range(511, 496);
        data_in_1_V_4_reg_949 = input_1_V_in_sig.read().range(671, 656);
        data_in_2_V_1_reg_804 = input_1_V_in_sig.read().range(207, 192);
        data_in_2_V_2_reg_854 = input_1_V_in_sig.read().range(367, 352);
        data_in_2_V_3_reg_904 = input_1_V_in_sig.read().range(527, 512);
        data_in_2_V_4_reg_954 = input_1_V_in_sig.read().range(687, 672);
        data_in_3_V_1_reg_809 = input_1_V_in_sig.read().range(223, 208);
        data_in_3_V_2_reg_859 = input_1_V_in_sig.read().range(383, 368);
        data_in_3_V_3_reg_909 = input_1_V_in_sig.read().range(543, 528);
        data_in_3_V_4_reg_959 = input_1_V_in_sig.read().range(703, 688);
        data_in_4_V_1_reg_814 = input_1_V_in_sig.read().range(239, 224);
        data_in_4_V_2_reg_864 = input_1_V_in_sig.read().range(399, 384);
        data_in_4_V_3_reg_914 = input_1_V_in_sig.read().range(559, 544);
        data_in_4_V_4_reg_964 = input_1_V_in_sig.read().range(719, 704);
        data_in_5_V_1_reg_819 = input_1_V_in_sig.read().range(255, 240);
        data_in_5_V_2_reg_869 = input_1_V_in_sig.read().range(415, 400);
        data_in_5_V_3_reg_919 = input_1_V_in_sig.read().range(575, 560);
        data_in_5_V_4_reg_969 = input_1_V_in_sig.read().range(735, 720);
        data_in_6_V_1_reg_824 = input_1_V_in_sig.read().range(271, 256);
        data_in_6_V_2_reg_874 = input_1_V_in_sig.read().range(431, 416);
        data_in_6_V_3_reg_924 = input_1_V_in_sig.read().range(591, 576);
        data_in_6_V_4_reg_974 = input_1_V_in_sig.read().range(751, 736);
        data_in_7_V_1_reg_829 = input_1_V_in_sig.read().range(287, 272);
        data_in_7_V_2_reg_879 = input_1_V_in_sig.read().range(447, 432);
        data_in_7_V_3_reg_929 = input_1_V_in_sig.read().range(607, 592);
        data_in_7_V_4_reg_979 = input_1_V_in_sig.read().range(767, 752);
        data_in_8_V_1_reg_834 = input_1_V_in_sig.read().range(303, 288);
        data_in_8_V_2_reg_884 = input_1_V_in_sig.read().range(463, 448);
        data_in_8_V_3_reg_934 = input_1_V_in_sig.read().range(623, 608);
        data_in_8_V_4_reg_984 = input_1_V_in_sig.read().range(783, 768);
        data_in_9_V_1_reg_839 = input_1_V_in_sig.read().range(319, 304);
        data_in_9_V_2_reg_889 = input_1_V_in_sig.read().range(479, 464);
        data_in_9_V_3_reg_939 = input_1_V_in_sig.read().range(639, 624);
        data_in_9_V_4_reg_989 = input_1_V_in_sig.read().range(799, 784);
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read())) {
        h_state_0_V_reg_994 = grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_ap_return.read();
    }
}

void myproject::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void myproject::thread_ap_CS_fsm_state104() {
    ap_CS_fsm_state104 = ap_CS_fsm.read()[103];
}

void myproject::thread_ap_CS_fsm_state105() {
    ap_CS_fsm_state105 = ap_CS_fsm.read()[104];
}

void myproject::thread_ap_CS_fsm_state21() {
    ap_CS_fsm_state21 = ap_CS_fsm.read()[20];
}

void myproject::thread_ap_CS_fsm_state22() {
    ap_CS_fsm_state22 = ap_CS_fsm.read()[21];
}

void myproject::thread_ap_CS_fsm_state42() {
    ap_CS_fsm_state42 = ap_CS_fsm.read()[41];
}

void myproject::thread_ap_CS_fsm_state43() {
    ap_CS_fsm_state43 = ap_CS_fsm.read()[42];
}

void myproject::thread_ap_CS_fsm_state63() {
    ap_CS_fsm_state63 = ap_CS_fsm.read()[62];
}

void myproject::thread_ap_CS_fsm_state64() {
    ap_CS_fsm_state64 = ap_CS_fsm.read()[63];
}

void myproject::thread_ap_CS_fsm_state84() {
    ap_CS_fsm_state84 = ap_CS_fsm.read()[83];
}

void myproject::thread_ap_CS_fsm_state85() {
    ap_CS_fsm_state85 = ap_CS_fsm.read()[84];
}

void myproject::thread_ap_NS_fsm_state22() {
    ap_NS_fsm_state22 = ap_NS_fsm.read()[21];
}

void myproject::thread_ap_NS_fsm_state43() {
    ap_NS_fsm_state43 = ap_NS_fsm.read()[42];
}

void myproject::thread_ap_NS_fsm_state64() {
    ap_NS_fsm_state64 = ap_NS_fsm.read()[63];
}

void myproject::thread_ap_NS_fsm_state85() {
    ap_NS_fsm_state85 = ap_NS_fsm.read()[84];
}

void myproject::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_const_logic_0, input_1_V_ap_vld_in_sig.read()));
}

void myproject::thread_ap_block_state1_ignore_call21() {
    ap_block_state1_ignore_call21 = (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_const_logic_0, input_1_V_ap_vld_in_sig.read()));
}

void myproject::thread_ap_done() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state105.read())) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void myproject::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void myproject::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state105.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void myproject::thread_data_in_0_V_fu_290_p1() {
    data_in_0_V_fu_290_p1 = input_1_V_in_sig.read().range(16-1, 0);
}

void myproject::thread_grp_dense_latency_ap_fixed_ap_fixed_config3_0_0_fu_284_ap_ce() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state104.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state105.read()))) {
        grp_dense_latency_ap_fixed_ap_fixed_config3_0_0_fu_284_ap_ce = ap_const_logic_1;
    } else {
        grp_dense_latency_ap_fixed_ap_fixed_config3_0_0_fu_284_ap_ce = ap_const_logic_0;
    }
}

void myproject::thread_grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_ap_ce() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || 
          esl_seteq<1,1,1>(ap_const_logic_0, input_1_V_ap_vld_in_sig.read())))) {
        grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_ap_ce = ap_const_logic_0;
    } else {
        grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_ap_ce = ap_const_logic_1;
    }
}

void myproject::thread_grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_ap_start() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_const_logic_0, input_1_V_ap_vld_in_sig.read())))) {
        grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_ap_start = ap_const_logic_1;
    } else {
        grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_ap_start = grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_ap_start_reg.read();
    }
}

void myproject::thread_grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_0_V_read() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state85.read())) {
        grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_0_V_read = data_in_0_V_4_reg_944.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state64.read())) {
        grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_0_V_read = data_in_0_V_3_reg_894.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state43.read())) {
        grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_0_V_read = data_in_0_V_2_reg_844.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state22.read())) {
        grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_0_V_read = data_in_0_V_1_reg_794.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_0_V_read = data_in_0_V_fu_290_p1.read();
    } else {
        grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_0_V_read = "XXXXXXXXXXXXXXXX";
    }
}

void myproject::thread_grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_1_V_read() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state85.read())) {
        grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_1_V_read = data_in_1_V_4_reg_949.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state64.read())) {
        grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_1_V_read = data_in_1_V_3_reg_899.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state43.read())) {
        grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_1_V_read = data_in_1_V_2_reg_849.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state22.read())) {
        grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_1_V_read = data_in_1_V_1_reg_799.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_1_V_read = input_1_V_in_sig.read().range(31, 16);
    } else {
        grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_1_V_read = "XXXXXXXXXXXXXXXX";
    }
}

void myproject::thread_grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_2_V_read() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state85.read())) {
        grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_2_V_read = data_in_2_V_4_reg_954.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state64.read())) {
        grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_2_V_read = data_in_2_V_3_reg_904.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state43.read())) {
        grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_2_V_read = data_in_2_V_2_reg_854.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state22.read())) {
        grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_2_V_read = data_in_2_V_1_reg_804.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_2_V_read = input_1_V_in_sig.read().range(47, 32);
    } else {
        grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_2_V_read = "XXXXXXXXXXXXXXXX";
    }
}

void myproject::thread_grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_3_V_read() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state85.read())) {
        grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_3_V_read = data_in_3_V_4_reg_959.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state64.read())) {
        grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_3_V_read = data_in_3_V_3_reg_909.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state43.read())) {
        grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_3_V_read = data_in_3_V_2_reg_859.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state22.read())) {
        grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_3_V_read = data_in_3_V_1_reg_809.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_3_V_read = input_1_V_in_sig.read().range(63, 48);
    } else {
        grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_3_V_read = "XXXXXXXXXXXXXXXX";
    }
}

void myproject::thread_grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_4_V_read() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state85.read())) {
        grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_4_V_read = data_in_4_V_4_reg_964.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state64.read())) {
        grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_4_V_read = data_in_4_V_3_reg_914.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state43.read())) {
        grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_4_V_read = data_in_4_V_2_reg_864.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state22.read())) {
        grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_4_V_read = data_in_4_V_1_reg_814.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_4_V_read = input_1_V_in_sig.read().range(79, 64);
    } else {
        grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_4_V_read = "XXXXXXXXXXXXXXXX";
    }
}

void myproject::thread_grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_5_V_read() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state85.read())) {
        grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_5_V_read = data_in_5_V_4_reg_969.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state64.read())) {
        grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_5_V_read = data_in_5_V_3_reg_919.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state43.read())) {
        grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_5_V_read = data_in_5_V_2_reg_869.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state22.read())) {
        grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_5_V_read = data_in_5_V_1_reg_819.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_5_V_read = input_1_V_in_sig.read().range(95, 80);
    } else {
        grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_5_V_read = "XXXXXXXXXXXXXXXX";
    }
}

void myproject::thread_grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_6_V_read() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state85.read())) {
        grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_6_V_read = data_in_6_V_4_reg_974.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state64.read())) {
        grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_6_V_read = data_in_6_V_3_reg_924.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state43.read())) {
        grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_6_V_read = data_in_6_V_2_reg_874.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state22.read())) {
        grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_6_V_read = data_in_6_V_1_reg_824.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_6_V_read = input_1_V_in_sig.read().range(111, 96);
    } else {
        grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_6_V_read = "XXXXXXXXXXXXXXXX";
    }
}

void myproject::thread_grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_7_V_read() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state85.read())) {
        grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_7_V_read = data_in_7_V_4_reg_979.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state64.read())) {
        grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_7_V_read = data_in_7_V_3_reg_929.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state43.read())) {
        grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_7_V_read = data_in_7_V_2_reg_879.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state22.read())) {
        grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_7_V_read = data_in_7_V_1_reg_829.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_7_V_read = input_1_V_in_sig.read().range(127, 112);
    } else {
        grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_7_V_read = "XXXXXXXXXXXXXXXX";
    }
}

void myproject::thread_grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_8_V_read() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state85.read())) {
        grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_8_V_read = data_in_8_V_4_reg_984.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state64.read())) {
        grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_8_V_read = data_in_8_V_3_reg_934.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state43.read())) {
        grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_8_V_read = data_in_8_V_2_reg_884.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state22.read())) {
        grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_8_V_read = data_in_8_V_1_reg_834.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_8_V_read = input_1_V_in_sig.read().range(143, 128);
    } else {
        grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_8_V_read = "XXXXXXXXXXXXXXXX";
    }
}

void myproject::thread_grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_9_V_read() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state85.read())) {
        grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_9_V_read = data_in_9_V_4_reg_989.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state64.read())) {
        grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_9_V_read = data_in_9_V_3_reg_939.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state43.read())) {
        grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_9_V_read = data_in_9_V_2_reg_889.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state22.read())) {
        grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_9_V_read = data_in_9_V_1_reg_839.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_9_V_read = input_1_V_in_sig.read().range(159, 144);
    } else {
        grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_data_9_V_read = "XXXXXXXXXXXXXXXX";
    }
}

void myproject::thread_grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_reset_state() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state22.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state43.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state64.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state85.read()))) {
        grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_reset_state =  (sc_logic) (ap_const_lv1_0[0]);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_reset_state =  (sc_logic) (ap_const_lv1_1[0]);
    } else {
        grp_gru_static_ap_fixed_ap_fixed_16_6_5_3_0_config2_s_fu_261_reset_state = sc_logic('X');
    }
}

void myproject::thread_input_1_V_ap_vld_in_sig() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, input_1_V_ap_vld.read())) {
        input_1_V_ap_vld_in_sig = input_1_V_ap_vld.read();
    } else {
        input_1_V_ap_vld_in_sig = input_1_V_ap_vld_preg.read();
    }
}

void myproject::thread_input_1_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        input_1_V_blk_n = input_1_V_ap_vld.read();
    } else {
        input_1_V_blk_n = ap_const_logic_1;
    }
}

void myproject::thread_input_1_V_in_sig() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, input_1_V_ap_vld.read())) {
        input_1_V_in_sig = input_1_V.read();
    } else {
        input_1_V_in_sig = input_1_V_preg.read();
    }
}

void myproject::thread_layer3_out_0_V() {
    layer3_out_0_V = grp_dense_latency_ap_fixed_ap_fixed_config3_0_0_fu_284_ap_return.read();
}

void myproject::thread_layer3_out_0_V_ap_vld() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state105.read())) {
        layer3_out_0_V_ap_vld = ap_const_logic_1;
    } else {
        layer3_out_0_V_ap_vld = ap_const_logic_0;
    }
}

void myproject::thread_ap_NS_fsm() {
    if (esl_seteq<1,105,105>(ap_CS_fsm.read(), ap_ST_fsm_state1))
    {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_const_logic_0, input_1_V_ap_vld_in_sig.read())))) {
            ap_NS_fsm = ap_ST_fsm_state2;
        } else {
            ap_NS_fsm = ap_ST_fsm_state1;
        }
    }
    else if (esl_seteq<1,105,105>(ap_CS_fsm.read(), ap_ST_fsm_state2))
    {
        ap_NS_fsm = ap_ST_fsm_state3;
    }
    else if (esl_seteq<1,105,105>(ap_CS_fsm.read(), ap_ST_fsm_state3))
    {
        ap_NS_fsm = ap_ST_fsm_state4;
    }
    else if (esl_seteq<1,105,105>(ap_CS_fsm.read(), ap_ST_fsm_state4))
    {
        ap_NS_fsm = ap_ST_fsm_state5;
    }
    else if (esl_seteq<1,105,105>(ap_CS_fsm.read(), ap_ST_fsm_state5))
    {
        ap_NS_fsm = ap_ST_fsm_state6;
    }
    else if (esl_seteq<1,105,105>(ap_CS_fsm.read(), ap_ST_fsm_state6))
    {
        ap_NS_fsm = ap_ST_fsm_state7;
    }
    else if (esl_seteq<1,105,105>(ap_CS_fsm.read(), ap_ST_fsm_state7))
    {
        ap_NS_fsm = ap_ST_fsm_state8;
    }
    else if (esl_seteq<1,105,105>(ap_CS_fsm.read(), ap_ST_fsm_state8))
    {
        ap_NS_fsm = ap_ST_fsm_state9;
    }
    else if (esl_seteq<1,105,105>(ap_CS_fsm.read(), ap_ST_fsm_state9))
    {
        ap_NS_fsm = ap_ST_fsm_state10;
    }
    else if (esl_seteq<1,105,105>(ap_CS_fsm.read(), ap_ST_fsm_state10))
    {
        ap_NS_fsm = ap_ST_fsm_state11;
    }
    else if (esl_seteq<1,105,105>(ap_CS_fsm.read(), ap_ST_fsm_state11))
    {
        ap_NS_fsm = ap_ST_fsm_state12;
    }
    else if (esl_seteq<1,105,105>(ap_CS_fsm.read(), ap_ST_fsm_state12))
    {
        ap_NS_fsm = ap_ST_fsm_state13;
    }
    else if (esl_seteq<1,105,105>(ap_CS_fsm.read(), ap_ST_fsm_state13))
    {
        ap_NS_fsm = ap_ST_fsm_state14;
    }
    else if (esl_seteq<1,105,105>(ap_CS_fsm.read(), ap_ST_fsm_state14))
    {
        ap_NS_fsm = ap_ST_fsm_state15;
    }
    else if (esl_seteq<1,105,105>(ap_CS_fsm.read(), ap_ST_fsm_state15))
    {
        ap_NS_fsm = ap_ST_fsm_state16;
    }
    else if (esl_seteq<1,105,105>(ap_CS_fsm.read(), ap_ST_fsm_state16))
    {
        ap_NS_fsm = ap_ST_fsm_state17;
    }
    else if (esl_seteq<1,105,105>(ap_CS_fsm.read(), ap_ST_fsm_state17))
    {
        ap_NS_fsm = ap_ST_fsm_state18;
    }
    else if (esl_seteq<1,105,105>(ap_CS_fsm.read(), ap_ST_fsm_state18))
    {
        ap_NS_fsm = ap_ST_fsm_state19;
    }
    else if (esl_seteq<1,105,105>(ap_CS_fsm.read(), ap_ST_fsm_state19))
    {
        ap_NS_fsm = ap_ST_fsm_state20;
    }
    else if (esl_seteq<1,105,105>(ap_CS_fsm.read(), ap_ST_fsm_state20))
    {
        ap_NS_fsm = ap_ST_fsm_state21;
    }
    else if (esl_seteq<1,105,105>(ap_CS_fsm.read(), ap_ST_fsm_state21))
    {
        ap_NS_fsm = ap_ST_fsm_state22;
    }
    else if (esl_seteq<1,105,105>(ap_CS_fsm.read(), ap_ST_fsm_state22))
    {
        ap_NS_fsm = ap_ST_fsm_state23;
    }
    else if (esl_seteq<1,105,105>(ap_CS_fsm.read(), ap_ST_fsm_state23))
    {
        ap_NS_fsm = ap_ST_fsm_state24;
    }
    else if (esl_seteq<1,105,105>(ap_CS_fsm.read(), ap_ST_fsm_state24))
    {
        ap_NS_fsm = ap_ST_fsm_state25;
    }
    else if (esl_seteq<1,105,105>(ap_CS_fsm.read(), ap_ST_fsm_state25))
    {
        ap_NS_fsm = ap_ST_fsm_state26;
    }
    else if (esl_seteq<1,105,105>(ap_CS_fsm.read(), ap_ST_fsm_state26))
    {
        ap_NS_fsm = ap_ST_fsm_state27;
    }
    else if (esl_seteq<1,105,105>(ap_CS_fsm.read(), ap_ST_fsm_state27))
    {
        ap_NS_fsm = ap_ST_fsm_state28;
    }
    else if (esl_seteq<1,105,105>(ap_CS_fsm.read(), ap_ST_fsm_state28))
    {
        ap_NS_fsm = ap_ST_fsm_state29;
    }
    else if (esl_seteq<1,105,105>(ap_CS_fsm.read(), ap_ST_fsm_state29))
    {
        ap_NS_fsm = ap_ST_fsm_state30;
    }
    else if (esl_seteq<1,105,105>(ap_CS_fsm.read(), ap_ST_fsm_state30))
    {
        ap_NS_fsm = ap_ST_fsm_state31;
    }
    else if (esl_seteq<1,105,105>(ap_CS_fsm.read(), ap_ST_fsm_state31))
    {
        ap_NS_fsm = ap_ST_fsm_state32;
    }
    else if (esl_seteq<1,105,105>(ap_CS_fsm.read(), ap_ST_fsm_state32))
    {
        ap_NS_fsm = ap_ST_fsm_state33;
    }
    else if (esl_seteq<1,105,105>(ap_CS_fsm.read(), ap_ST_fsm_state33))
    {
        ap_NS_fsm = ap_ST_fsm_state34;
    }
    else if (esl_seteq<1,105,105>(ap_CS_fsm.read(), ap_ST_fsm_state34))
    {
        ap_NS_fsm = ap_ST_fsm_state35;
    }
    else if (esl_seteq<1,105,105>(ap_CS_fsm.read(), ap_ST_fsm_state35))
    {
        ap_NS_fsm = ap_ST_fsm_state36;
    }
    else if (esl_seteq<1,105,105>(ap_CS_fsm.read(), ap_ST_fsm_state36))
    {
        ap_NS_fsm = ap_ST_fsm_state37;
    }
    else if (esl_seteq<1,105,105>(ap_CS_fsm.read(), ap_ST_fsm_state37))
    {
        ap_NS_fsm = ap_ST_fsm_state38;
    }
    else if (esl_seteq<1,105,105>(ap_CS_fsm.read(), ap_ST_fsm_state38))
    {
        ap_NS_fsm = ap_ST_fsm_state39;
    }
    else if (esl_seteq<1,105,105>(ap_CS_fsm.read(), ap_ST_fsm_state39))
    {
        ap_NS_fsm = ap_ST_fsm_state40;
    }
    else if (esl_seteq<1,105,105>(ap_CS_fsm.read(), ap_ST_fsm_state40))
    {
        ap_NS_fsm = ap_ST_fsm_state41;
    }
    else if (esl_seteq<1,105,105>(ap_CS_fsm.read(), ap_ST_fsm_state41))
    {
        ap_NS_fsm = ap_ST_fsm_state42;
    }
    else if (esl_seteq<1,105,105>(ap_CS_fsm.read(), ap_ST_fsm_state42))
    {
        ap_NS_fsm = ap_ST_fsm_state43;
    }
    else if (esl_seteq<1,105,105>(ap_CS_fsm.read(), ap_ST_fsm_state43))
    {
        ap_NS_fsm = ap_ST_fsm_state44;
    }
    else if (esl_seteq<1,105,105>(ap_CS_fsm.read(), ap_ST_fsm_state44))
    {
        ap_NS_fsm = ap_ST_fsm_state45;
    }
    else if (esl_seteq<1,105,105>(ap_CS_fsm.read(), ap_ST_fsm_state45))
    {
        ap_NS_fsm = ap_ST_fsm_state46;
    }
    else if (esl_seteq<1,105,105>(ap_CS_fsm.read(), ap_ST_fsm_state46))
    {
        ap_NS_fsm = ap_ST_fsm_state47;
    }
    else if (esl_seteq<1,105,105>(ap_CS_fsm.read(), ap_ST_fsm_state47))
    {
        ap_NS_fsm = ap_ST_fsm_state48;
    }
    else if (esl_seteq<1,105,105>(ap_CS_fsm.read(), ap_ST_fsm_state48))
    {
        ap_NS_fsm = ap_ST_fsm_state49;
    }
    else if (esl_seteq<1,105,105>(ap_CS_fsm.read(), ap_ST_fsm_state49))
    {
        ap_NS_fsm = ap_ST_fsm_state50;
    }
    else if (esl_seteq<1,105,105>(ap_CS_fsm.read(), ap_ST_fsm_state50))
    {
        ap_NS_fsm = ap_ST_fsm_state51;
    }
    else if (esl_seteq<1,105,105>(ap_CS_fsm.read(), ap_ST_fsm_state51))
    {
        ap_NS_fsm = ap_ST_fsm_state52;
    }
    else if (esl_seteq<1,105,105>(ap_CS_fsm.read(), ap_ST_fsm_state52))
    {
        ap_NS_fsm = ap_ST_fsm_state53;
    }
    else if (esl_seteq<1,105,105>(ap_CS_fsm.read(), ap_ST_fsm_state53))
    {
        ap_NS_fsm = ap_ST_fsm_state54;
    }
    else if (esl_seteq<1,105,105>(ap_CS_fsm.read(), ap_ST_fsm_state54))
    {
        ap_NS_fsm = ap_ST_fsm_state55;
    }
    else if (esl_seteq<1,105,105>(ap_CS_fsm.read(), ap_ST_fsm_state55))
    {
        ap_NS_fsm = ap_ST_fsm_state56;
    }
    else if (esl_seteq<1,105,105>(ap_CS_fsm.read(), ap_ST_fsm_state56))
    {
        ap_NS_fsm = ap_ST_fsm_state57;
    }
    else if (esl_seteq<1,105,105>(ap_CS_fsm.read(), ap_ST_fsm_state57))
    {
        ap_NS_fsm = ap_ST_fsm_state58;
    }
    else if (esl_seteq<1,105,105>(ap_CS_fsm.read(), ap_ST_fsm_state58))
    {
        ap_NS_fsm = ap_ST_fsm_state59;
    }
    else if (esl_seteq<1,105,105>(ap_CS_fsm.read(), ap_ST_fsm_state59))
    {
        ap_NS_fsm = ap_ST_fsm_state60;
    }
    else if (esl_seteq<1,105,105>(ap_CS_fsm.read(), ap_ST_fsm_state60))
    {
        ap_NS_fsm = ap_ST_fsm_state61;
    }
    else if (esl_seteq<1,105,105>(ap_CS_fsm.read(), ap_ST_fsm_state61))
    {
        ap_NS_fsm = ap_ST_fsm_state62;
    }
    else if (esl_seteq<1,105,105>(ap_CS_fsm.read(), ap_ST_fsm_state62))
    {
        ap_NS_fsm = ap_ST_fsm_state63;
    }
    else if (esl_seteq<1,105,105>(ap_CS_fsm.read(), ap_ST_fsm_state63))
    {
        ap_NS_fsm = ap_ST_fsm_state64;
    }
    else if (esl_seteq<1,105,105>(ap_CS_fsm.read(), ap_ST_fsm_state64))
    {
        ap_NS_fsm = ap_ST_fsm_state65;
    }
    else if (esl_seteq<1,105,105>(ap_CS_fsm.read(), ap_ST_fsm_state65))
    {
        ap_NS_fsm = ap_ST_fsm_state66;
    }
    else if (esl_seteq<1,105,105>(ap_CS_fsm.read(), ap_ST_fsm_state66))
    {
        ap_NS_fsm = ap_ST_fsm_state67;
    }
    else if (esl_seteq<1,105,105>(ap_CS_fsm.read(), ap_ST_fsm_state67))
    {
        ap_NS_fsm = ap_ST_fsm_state68;
    }
    else if (esl_seteq<1,105,105>(ap_CS_fsm.read(), ap_ST_fsm_state68))
    {
        ap_NS_fsm = ap_ST_fsm_state69;
    }
    else if (esl_seteq<1,105,105>(ap_CS_fsm.read(), ap_ST_fsm_state69))
    {
        ap_NS_fsm = ap_ST_fsm_state70;
    }
    else if (esl_seteq<1,105,105>(ap_CS_fsm.read(), ap_ST_fsm_state70))
    {
        ap_NS_fsm = ap_ST_fsm_state71;
    }
    else if (esl_seteq<1,105,105>(ap_CS_fsm.read(), ap_ST_fsm_state71))
    {
        ap_NS_fsm = ap_ST_fsm_state72;
    }
    else if (esl_seteq<1,105,105>(ap_CS_fsm.read(), ap_ST_fsm_state72))
    {
        ap_NS_fsm = ap_ST_fsm_state73;
    }
    else if (esl_seteq<1,105,105>(ap_CS_fsm.read(), ap_ST_fsm_state73))
    {
        ap_NS_fsm = ap_ST_fsm_state74;
    }
    else if (esl_seteq<1,105,105>(ap_CS_fsm.read(), ap_ST_fsm_state74))
    {
        ap_NS_fsm = ap_ST_fsm_state75;
    }
    else if (esl_seteq<1,105,105>(ap_CS_fsm.read(), ap_ST_fsm_state75))
    {
        ap_NS_fsm = ap_ST_fsm_state76;
    }
    else if (esl_seteq<1,105,105>(ap_CS_fsm.read(), ap_ST_fsm_state76))
    {
        ap_NS_fsm = ap_ST_fsm_state77;
    }
    else if (esl_seteq<1,105,105>(ap_CS_fsm.read(), ap_ST_fsm_state77))
    {
        ap_NS_fsm = ap_ST_fsm_state78;
    }
    else if (esl_seteq<1,105,105>(ap_CS_fsm.read(), ap_ST_fsm_state78))
    {
        ap_NS_fsm = ap_ST_fsm_state79;
    }
    else if (esl_seteq<1,105,105>(ap_CS_fsm.read(), ap_ST_fsm_state79))
    {
        ap_NS_fsm = ap_ST_fsm_state80;
    }
    else if (esl_seteq<1,105,105>(ap_CS_fsm.read(), ap_ST_fsm_state80))
    {
        ap_NS_fsm = ap_ST_fsm_state81;
    }
    else if (esl_seteq<1,105,105>(ap_CS_fsm.read(), ap_ST_fsm_state81))
    {
        ap_NS_fsm = ap_ST_fsm_state82;
    }
    else if (esl_seteq<1,105,105>(ap_CS_fsm.read(), ap_ST_fsm_state82))
    {
        ap_NS_fsm = ap_ST_fsm_state83;
    }
    else if (esl_seteq<1,105,105>(ap_CS_fsm.read(), ap_ST_fsm_state83))
    {
        ap_NS_fsm = ap_ST_fsm_state84;
    }
    else if (esl_seteq<1,105,105>(ap_CS_fsm.read(), ap_ST_fsm_state84))
    {
        ap_NS_fsm = ap_ST_fsm_state85;
    }
    else if (esl_seteq<1,105,105>(ap_CS_fsm.read(), ap_ST_fsm_state85))
    {
        ap_NS_fsm = ap_ST_fsm_state86;
    }
    else if (esl_seteq<1,105,105>(ap_CS_fsm.read(), ap_ST_fsm_state86))
    {
        ap_NS_fsm = ap_ST_fsm_state87;
    }
    else if (esl_seteq<1,105,105>(ap_CS_fsm.read(), ap_ST_fsm_state87))
    {
        ap_NS_fsm = ap_ST_fsm_state88;
    }
    else if (esl_seteq<1,105,105>(ap_CS_fsm.read(), ap_ST_fsm_state88))
    {
        ap_NS_fsm = ap_ST_fsm_state89;
    }
    else if (esl_seteq<1,105,105>(ap_CS_fsm.read(), ap_ST_fsm_state89))
    {
        ap_NS_fsm = ap_ST_fsm_state90;
    }
    else if (esl_seteq<1,105,105>(ap_CS_fsm.read(), ap_ST_fsm_state90))
    {
        ap_NS_fsm = ap_ST_fsm_state91;
    }
    else if (esl_seteq<1,105,105>(ap_CS_fsm.read(), ap_ST_fsm_state91))
    {
        ap_NS_fsm = ap_ST_fsm_state92;
    }
    else if (esl_seteq<1,105,105>(ap_CS_fsm.read(), ap_ST_fsm_state92))
    {
        ap_NS_fsm = ap_ST_fsm_state93;
    }
    else if (esl_seteq<1,105,105>(ap_CS_fsm.read(), ap_ST_fsm_state93))
    {
        ap_NS_fsm = ap_ST_fsm_state94;
    }
    else if (esl_seteq<1,105,105>(ap_CS_fsm.read(), ap_ST_fsm_state94))
    {
        ap_NS_fsm = ap_ST_fsm_state95;
    }
    else if (esl_seteq<1,105,105>(ap_CS_fsm.read(), ap_ST_fsm_state95))
    {
        ap_NS_fsm = ap_ST_fsm_state96;
    }
    else if (esl_seteq<1,105,105>(ap_CS_fsm.read(), ap_ST_fsm_state96))
    {
        ap_NS_fsm = ap_ST_fsm_state97;
    }
    else if (esl_seteq<1,105,105>(ap_CS_fsm.read(), ap_ST_fsm_state97))
    {
        ap_NS_fsm = ap_ST_fsm_state98;
    }
    else if (esl_seteq<1,105,105>(ap_CS_fsm.read(), ap_ST_fsm_state98))
    {
        ap_NS_fsm = ap_ST_fsm_state99;
    }
    else if (esl_seteq<1,105,105>(ap_CS_fsm.read(), ap_ST_fsm_state99))
    {
        ap_NS_fsm = ap_ST_fsm_state100;
    }
    else if (esl_seteq<1,105,105>(ap_CS_fsm.read(), ap_ST_fsm_state100))
    {
        ap_NS_fsm = ap_ST_fsm_state101;
    }
    else if (esl_seteq<1,105,105>(ap_CS_fsm.read(), ap_ST_fsm_state101))
    {
        ap_NS_fsm = ap_ST_fsm_state102;
    }
    else if (esl_seteq<1,105,105>(ap_CS_fsm.read(), ap_ST_fsm_state102))
    {
        ap_NS_fsm = ap_ST_fsm_state103;
    }
    else if (esl_seteq<1,105,105>(ap_CS_fsm.read(), ap_ST_fsm_state103))
    {
        ap_NS_fsm = ap_ST_fsm_state104;
    }
    else if (esl_seteq<1,105,105>(ap_CS_fsm.read(), ap_ST_fsm_state104))
    {
        ap_NS_fsm = ap_ST_fsm_state105;
    }
    else if (esl_seteq<1,105,105>(ap_CS_fsm.read(), ap_ST_fsm_state105))
    {
        ap_NS_fsm = ap_ST_fsm_state1;
    }
    else
    {
        ap_NS_fsm =  (sc_lv<105>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}
void myproject::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"input_1_V\" :  \"" << input_1_V.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"input_1_V_ap_vld\" :  \"" << input_1_V_ap_vld.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"layer3_out_0_V\" :  \"" << layer3_out_0_V.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"layer3_out_0_V_ap_vld\" :  \"" << layer3_out_0_V_ap_vld.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"layer3_out_1_V\" :  \"" << layer3_out_1_V.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"layer3_out_1_V_ap_vld\" :  \"" << layer3_out_1_V_ap_vld.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"layer3_out_2_V\" :  \"" << layer3_out_2_V.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"layer3_out_2_V_ap_vld\" :  \"" << layer3_out_2_V_ap_vld.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"layer3_out_3_V\" :  \"" << layer3_out_3_V.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"layer3_out_3_V_ap_vld\" :  \"" << layer3_out_3_V_ap_vld.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"layer3_out_4_V\" :  \"" << layer3_out_4_V.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"layer3_out_4_V_ap_vld\" :  \"" << layer3_out_4_V_ap_vld.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

