-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2019.2
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity sigmoid_ap_fixed_ap_fixed_sigmoid_config2_recr_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ap_ce : IN STD_LOGIC;
    data_0_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    data_1_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    data_2_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    data_3_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    data_4_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    data_5_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    data_6_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    data_7_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_3 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_4 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_5 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_6 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_7 : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of sigmoid_ap_fixed_ap_fixed_sigmoid_config2_recr_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv26_3FFFFF1 : STD_LOGIC_VECTOR (25 downto 0) := "11111111111111111111110001";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv13_1 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000001";
    constant ap_const_lv13_200 : STD_LOGIC_VECTOR (12 downto 0) := "0001000000000";
    constant ap_const_lv12_200 : STD_LOGIC_VECTOR (11 downto 0) := "001000000000";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv10_3FF : STD_LOGIC_VECTOR (9 downto 0) := "1111111111";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal sigmoid_table2_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal sigmoid_table2_ce0 : STD_LOGIC;
    signal sigmoid_table2_q0 : STD_LOGIC_VECTOR (9 downto 0);
    signal sigmoid_table2_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal sigmoid_table2_ce1 : STD_LOGIC;
    signal sigmoid_table2_q1 : STD_LOGIC_VECTOR (9 downto 0);
    signal sigmoid_table2_address2 : STD_LOGIC_VECTOR (9 downto 0);
    signal sigmoid_table2_ce2 : STD_LOGIC;
    signal sigmoid_table2_q2 : STD_LOGIC_VECTOR (9 downto 0);
    signal sigmoid_table2_address3 : STD_LOGIC_VECTOR (9 downto 0);
    signal sigmoid_table2_ce3 : STD_LOGIC;
    signal sigmoid_table2_q3 : STD_LOGIC_VECTOR (9 downto 0);
    signal sigmoid_table2_address4 : STD_LOGIC_VECTOR (9 downto 0);
    signal sigmoid_table2_ce4 : STD_LOGIC;
    signal sigmoid_table2_q4 : STD_LOGIC_VECTOR (9 downto 0);
    signal sigmoid_table2_address5 : STD_LOGIC_VECTOR (9 downto 0);
    signal sigmoid_table2_ce5 : STD_LOGIC;
    signal sigmoid_table2_q5 : STD_LOGIC_VECTOR (9 downto 0);
    signal sigmoid_table2_address6 : STD_LOGIC_VECTOR (9 downto 0);
    signal sigmoid_table2_ce6 : STD_LOGIC;
    signal sigmoid_table2_q6 : STD_LOGIC_VECTOR (9 downto 0);
    signal sigmoid_table2_address7 : STD_LOGIC_VECTOR (9 downto 0);
    signal sigmoid_table2_ce7 : STD_LOGIC;
    signal sigmoid_table2_q7 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln850_fu_277_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal select_ln850_reg_1337 : STD_LOGIC_VECTOR (12 downto 0);
    signal trunc_ln147_fu_285_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal trunc_ln147_reg_1342 : STD_LOGIC_VECTOR (11 downto 0);
    signal select_ln850_4_fu_349_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal select_ln850_4_reg_1347 : STD_LOGIC_VECTOR (12 downto 0);
    signal trunc_ln147_1_fu_357_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal trunc_ln147_1_reg_1352 : STD_LOGIC_VECTOR (11 downto 0);
    signal select_ln850_5_fu_421_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal select_ln850_5_reg_1357 : STD_LOGIC_VECTOR (12 downto 0);
    signal trunc_ln147_2_fu_429_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal trunc_ln147_2_reg_1362 : STD_LOGIC_VECTOR (11 downto 0);
    signal select_ln850_6_fu_493_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal select_ln850_6_reg_1367 : STD_LOGIC_VECTOR (12 downto 0);
    signal trunc_ln147_3_fu_501_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal trunc_ln147_3_reg_1372 : STD_LOGIC_VECTOR (11 downto 0);
    signal select_ln850_7_fu_565_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal select_ln850_7_reg_1377 : STD_LOGIC_VECTOR (12 downto 0);
    signal trunc_ln147_4_fu_573_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal trunc_ln147_4_reg_1382 : STD_LOGIC_VECTOR (11 downto 0);
    signal select_ln850_8_fu_637_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal select_ln850_8_reg_1387 : STD_LOGIC_VECTOR (12 downto 0);
    signal trunc_ln147_5_fu_645_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal trunc_ln147_5_reg_1392 : STD_LOGIC_VECTOR (11 downto 0);
    signal select_ln850_9_fu_709_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal select_ln850_9_reg_1397 : STD_LOGIC_VECTOR (12 downto 0);
    signal trunc_ln147_6_fu_717_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal trunc_ln147_6_reg_1402 : STD_LOGIC_VECTOR (11 downto 0);
    signal select_ln850_10_fu_781_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal select_ln850_10_reg_1407 : STD_LOGIC_VECTOR (12 downto 0);
    signal trunc_ln147_7_fu_789_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal trunc_ln147_7_reg_1412 : STD_LOGIC_VECTOR (11 downto 0);
    signal select_ln149_fu_839_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln149_reg_1417 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln149_1_fu_893_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln149_1_reg_1422 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln149_2_fu_947_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln149_2_reg_1427 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln149_3_fu_1001_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln149_3_reg_1432 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln149_4_fu_1055_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln149_4_reg_1437 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln149_5_fu_1109_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln149_5_reg_1442 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln149_6_fu_1163_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln149_6_reg_1447 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln149_7_fu_1217_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln149_7_reg_1452 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal zext_ln150_fu_1225_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln150_1_fu_1229_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln150_2_fu_1233_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln150_3_fu_1237_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln150_4_fu_1241_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln150_5_fu_1245_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln150_6_fu_1249_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln150_7_fu_1253_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_fu_225_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal shl_ln_fu_217_p3 : STD_LOGIC_VECTOR (25 downto 0);
    signal trunc_ln851_fu_245_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_Result_4_fu_249_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln850_fu_235_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal icmp_ln851_fu_257_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln700_fu_263_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal icmp_ln850_fu_239_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln851_fu_269_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_9_fu_297_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal shl_ln1118_4_fu_289_p3 : STD_LOGIC_VECTOR (25 downto 0);
    signal trunc_ln851_4_fu_317_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_Result_4_1_fu_321_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln850_4_fu_307_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal icmp_ln851_1_fu_329_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln700_4_fu_335_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal icmp_ln850_4_fu_311_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln851_1_fu_341_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_1_fu_369_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal shl_ln1118_5_fu_361_p3 : STD_LOGIC_VECTOR (25 downto 0);
    signal trunc_ln851_5_fu_389_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_Result_4_2_fu_393_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln850_5_fu_379_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal icmp_ln851_2_fu_401_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln700_5_fu_407_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal icmp_ln850_5_fu_383_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln851_2_fu_413_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_3_fu_441_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal shl_ln1118_6_fu_433_p3 : STD_LOGIC_VECTOR (25 downto 0);
    signal trunc_ln851_6_fu_461_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_Result_4_3_fu_465_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln850_6_fu_451_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal icmp_ln851_3_fu_473_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln700_6_fu_479_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal icmp_ln850_6_fu_455_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln851_3_fu_485_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_5_fu_513_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal shl_ln1118_7_fu_505_p3 : STD_LOGIC_VECTOR (25 downto 0);
    signal trunc_ln851_7_fu_533_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_Result_4_4_fu_537_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln850_7_fu_523_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal icmp_ln851_4_fu_545_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln700_7_fu_551_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal icmp_ln850_7_fu_527_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln851_4_fu_557_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_7_fu_585_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal shl_ln1118_8_fu_577_p3 : STD_LOGIC_VECTOR (25 downto 0);
    signal trunc_ln851_8_fu_605_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_Result_4_5_fu_609_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln850_8_fu_595_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal icmp_ln851_5_fu_617_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln700_8_fu_623_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal icmp_ln850_8_fu_599_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln851_5_fu_629_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_s_fu_657_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal shl_ln1118_9_fu_649_p3 : STD_LOGIC_VECTOR (25 downto 0);
    signal trunc_ln851_9_fu_677_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_Result_4_6_fu_681_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln850_9_fu_667_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal icmp_ln851_6_fu_689_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln700_9_fu_695_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal icmp_ln850_9_fu_671_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln851_6_fu_701_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_2_fu_729_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal shl_ln1118_s_fu_721_p3 : STD_LOGIC_VECTOR (25 downto 0);
    signal trunc_ln851_10_fu_749_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_Result_4_7_fu_753_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln850_10_fu_739_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal icmp_ln851_7_fu_761_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln700_10_fu_767_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal icmp_ln850_10_fu_743_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln851_7_fu_773_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln147_fu_793_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_12_fu_803_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln147_8_fu_798_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal select_ln148_fu_811_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_14_fu_823_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln149_fu_833_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln148_fu_819_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln147_1_fu_847_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_15_fu_857_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln147_9_fu_852_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal select_ln148_1_fu_865_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_16_fu_877_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln149_1_fu_887_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln148_1_fu_873_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln147_2_fu_901_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_17_fu_911_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln147_10_fu_906_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal select_ln148_2_fu_919_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_18_fu_931_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln149_2_fu_941_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln148_2_fu_927_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln147_3_fu_955_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_19_fu_965_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln147_11_fu_960_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal select_ln148_3_fu_973_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_20_fu_985_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln149_3_fu_995_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln148_3_fu_981_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln147_4_fu_1009_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_21_fu_1019_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln147_12_fu_1014_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal select_ln148_4_fu_1027_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_22_fu_1039_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln149_4_fu_1049_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln148_4_fu_1035_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln147_5_fu_1063_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_23_fu_1073_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln147_13_fu_1068_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal select_ln148_5_fu_1081_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_24_fu_1093_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln149_5_fu_1103_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln148_5_fu_1089_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln147_6_fu_1117_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_25_fu_1127_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln147_14_fu_1122_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal select_ln148_6_fu_1135_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_26_fu_1147_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln149_6_fu_1157_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln148_6_fu_1143_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln147_7_fu_1171_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_27_fu_1181_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln147_15_fu_1176_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal select_ln148_7_fu_1189_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_28_fu_1201_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln149_7_fu_1211_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln148_7_fu_1197_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln703_fu_1257_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln703_1_fu_1261_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln703_2_fu_1265_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln703_3_fu_1269_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln703_4_fu_1273_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln703_5_fu_1277_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln703_6_fu_1281_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln703_7_fu_1285_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_idle_pp0_0to2 : STD_LOGIC;
    signal ap_reset_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;

    component sigmoid_ap_fixed_ap_fixed_sigmoid_config2_recr_s_sigmoid_bkb IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        address1 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        address2 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce2 : IN STD_LOGIC;
        q2 : OUT STD_LOGIC_VECTOR (9 downto 0);
        address3 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce3 : IN STD_LOGIC;
        q3 : OUT STD_LOGIC_VECTOR (9 downto 0);
        address4 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce4 : IN STD_LOGIC;
        q4 : OUT STD_LOGIC_VECTOR (9 downto 0);
        address5 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce5 : IN STD_LOGIC;
        q5 : OUT STD_LOGIC_VECTOR (9 downto 0);
        address6 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce6 : IN STD_LOGIC;
        q6 : OUT STD_LOGIC_VECTOR (9 downto 0);
        address7 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce7 : IN STD_LOGIC;
        q7 : OUT STD_LOGIC_VECTOR (9 downto 0) );
    end component;



begin
    sigmoid_table2_U : component sigmoid_ap_fixed_ap_fixed_sigmoid_config2_recr_s_sigmoid_bkb
    generic map (
        DataWidth => 10,
        AddressRange => 1024,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => sigmoid_table2_address0,
        ce0 => sigmoid_table2_ce0,
        q0 => sigmoid_table2_q0,
        address1 => sigmoid_table2_address1,
        ce1 => sigmoid_table2_ce1,
        q1 => sigmoid_table2_q1,
        address2 => sigmoid_table2_address2,
        ce2 => sigmoid_table2_ce2,
        q2 => sigmoid_table2_q2,
        address3 => sigmoid_table2_address3,
        ce3 => sigmoid_table2_ce3,
        q3 => sigmoid_table2_q3,
        address4 => sigmoid_table2_address4,
        ce4 => sigmoid_table2_ce4,
        q4 => sigmoid_table2_q4,
        address5 => sigmoid_table2_address5,
        ce5 => sigmoid_table2_ce5,
        q5 => sigmoid_table2_q5,
        address6 => sigmoid_table2_address6,
        ce6 => sigmoid_table2_ce6,
        q6 => sigmoid_table2_q6,
        address7 => sigmoid_table2_address7,
        ce7 => sigmoid_table2_ce7,
        q7 => sigmoid_table2_q7);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_ce) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                select_ln149_1_reg_1422 <= select_ln149_1_fu_893_p3;
                select_ln149_2_reg_1427 <= select_ln149_2_fu_947_p3;
                select_ln149_3_reg_1432 <= select_ln149_3_fu_1001_p3;
                select_ln149_4_reg_1437 <= select_ln149_4_fu_1055_p3;
                select_ln149_5_reg_1442 <= select_ln149_5_fu_1109_p3;
                select_ln149_6_reg_1447 <= select_ln149_6_fu_1163_p3;
                select_ln149_7_reg_1452 <= select_ln149_7_fu_1217_p3;
                select_ln149_reg_1417 <= select_ln149_fu_839_p3;
                select_ln850_10_reg_1407 <= select_ln850_10_fu_781_p3;
                select_ln850_4_reg_1347 <= select_ln850_4_fu_349_p3;
                select_ln850_5_reg_1357 <= select_ln850_5_fu_421_p3;
                select_ln850_6_reg_1367 <= select_ln850_6_fu_493_p3;
                select_ln850_7_reg_1377 <= select_ln850_7_fu_565_p3;
                select_ln850_8_reg_1387 <= select_ln850_8_fu_637_p3;
                select_ln850_9_reg_1397 <= select_ln850_9_fu_709_p3;
                select_ln850_reg_1337 <= select_ln850_fu_277_p3;
                trunc_ln147_1_reg_1352 <= trunc_ln147_1_fu_357_p1;
                trunc_ln147_2_reg_1362 <= trunc_ln147_2_fu_429_p1;
                trunc_ln147_3_reg_1372 <= trunc_ln147_3_fu_501_p1;
                trunc_ln147_4_reg_1382 <= trunc_ln147_4_fu_573_p1;
                trunc_ln147_5_reg_1392 <= trunc_ln147_5_fu_645_p1;
                trunc_ln147_6_reg_1402 <= trunc_ln147_6_fu_717_p1;
                trunc_ln147_7_reg_1412 <= trunc_ln147_7_fu_789_p1;
                trunc_ln147_reg_1342 <= trunc_ln147_fu_285_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_reset_idle_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln147_10_fu_906_p2 <= std_logic_vector(unsigned(ap_const_lv12_200) + unsigned(trunc_ln147_2_reg_1362));
    add_ln147_11_fu_960_p2 <= std_logic_vector(unsigned(ap_const_lv12_200) + unsigned(trunc_ln147_3_reg_1372));
    add_ln147_12_fu_1014_p2 <= std_logic_vector(unsigned(ap_const_lv12_200) + unsigned(trunc_ln147_4_reg_1382));
    add_ln147_13_fu_1068_p2 <= std_logic_vector(unsigned(ap_const_lv12_200) + unsigned(trunc_ln147_5_reg_1392));
    add_ln147_14_fu_1122_p2 <= std_logic_vector(unsigned(ap_const_lv12_200) + unsigned(trunc_ln147_6_reg_1402));
    add_ln147_15_fu_1176_p2 <= std_logic_vector(unsigned(ap_const_lv12_200) + unsigned(trunc_ln147_7_reg_1412));
    add_ln147_1_fu_847_p2 <= std_logic_vector(unsigned(ap_const_lv13_200) + unsigned(select_ln850_4_reg_1347));
    add_ln147_2_fu_901_p2 <= std_logic_vector(unsigned(ap_const_lv13_200) + unsigned(select_ln850_5_reg_1357));
    add_ln147_3_fu_955_p2 <= std_logic_vector(unsigned(ap_const_lv13_200) + unsigned(select_ln850_6_reg_1367));
    add_ln147_4_fu_1009_p2 <= std_logic_vector(unsigned(ap_const_lv13_200) + unsigned(select_ln850_7_reg_1377));
    add_ln147_5_fu_1063_p2 <= std_logic_vector(unsigned(ap_const_lv13_200) + unsigned(select_ln850_8_reg_1387));
    add_ln147_6_fu_1117_p2 <= std_logic_vector(unsigned(ap_const_lv13_200) + unsigned(select_ln850_9_reg_1397));
    add_ln147_7_fu_1171_p2 <= std_logic_vector(unsigned(ap_const_lv13_200) + unsigned(select_ln850_10_reg_1407));
    add_ln147_8_fu_798_p2 <= std_logic_vector(unsigned(ap_const_lv12_200) + unsigned(trunc_ln147_reg_1342));
    add_ln147_9_fu_852_p2 <= std_logic_vector(unsigned(ap_const_lv12_200) + unsigned(trunc_ln147_1_reg_1352));
    add_ln147_fu_793_p2 <= std_logic_vector(unsigned(ap_const_lv13_200) + unsigned(select_ln850_reg_1337));
    add_ln700_10_fu_767_p2 <= std_logic_vector(unsigned(ap_const_lv13_1) + unsigned(sext_ln850_10_fu_739_p1));
    add_ln700_4_fu_335_p2 <= std_logic_vector(unsigned(ap_const_lv13_1) + unsigned(sext_ln850_4_fu_307_p1));
    add_ln700_5_fu_407_p2 <= std_logic_vector(unsigned(ap_const_lv13_1) + unsigned(sext_ln850_5_fu_379_p1));
    add_ln700_6_fu_479_p2 <= std_logic_vector(unsigned(ap_const_lv13_1) + unsigned(sext_ln850_6_fu_451_p1));
    add_ln700_7_fu_551_p2 <= std_logic_vector(unsigned(ap_const_lv13_1) + unsigned(sext_ln850_7_fu_523_p1));
    add_ln700_8_fu_623_p2 <= std_logic_vector(unsigned(ap_const_lv13_1) + unsigned(sext_ln850_8_fu_595_p1));
    add_ln700_9_fu_695_p2 <= std_logic_vector(unsigned(ap_const_lv13_1) + unsigned(sext_ln850_9_fu_667_p1));
    add_ln700_fu_263_p2 <= std_logic_vector(unsigned(ap_const_lv13_1) + unsigned(sext_ln850_fu_235_p1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_start)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_start = ap_const_logic_0) and (ap_start = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_start, ap_ce)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_const_logic_0 = ap_ce) or ((ap_start = ap_const_logic_0) and (ap_start = ap_const_logic_1)));
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_start)
    begin
                ap_block_state1_pp0_stage0_iter0 <= (ap_start = ap_const_logic_0);
    end process;

        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001, ap_ce)
    begin
        if ((((ap_start = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_logic_1 = ap_ce) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start;

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_idle_pp0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to2_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0_0to2 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to2 <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_ce)
    begin
        if (((ap_const_logic_1 = ap_ce) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_reset_idle_pp0_assign_proc : process(ap_start, ap_idle_pp0_0to2)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0_0to2 = ap_const_logic_1))) then 
            ap_reset_idle_pp0 <= ap_const_logic_1;
        else 
            ap_reset_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_return_0 <= zext_ln703_fu_1257_p1;
    ap_return_1 <= zext_ln703_1_fu_1261_p1;
    ap_return_2 <= zext_ln703_2_fu_1265_p1;
    ap_return_3 <= zext_ln703_3_fu_1269_p1;
    ap_return_4 <= zext_ln703_4_fu_1273_p1;
    ap_return_5 <= zext_ln703_5_fu_1277_p1;
    ap_return_6 <= zext_ln703_6_fu_1281_p1;
    ap_return_7 <= zext_ln703_7_fu_1285_p1;
    icmp_ln149_1_fu_887_p2 <= "0" when (tmp_16_fu_877_p4 = ap_const_lv2_0) else "1";
    icmp_ln149_2_fu_941_p2 <= "0" when (tmp_18_fu_931_p4 = ap_const_lv2_0) else "1";
    icmp_ln149_3_fu_995_p2 <= "0" when (tmp_20_fu_985_p4 = ap_const_lv2_0) else "1";
    icmp_ln149_4_fu_1049_p2 <= "0" when (tmp_22_fu_1039_p4 = ap_const_lv2_0) else "1";
    icmp_ln149_5_fu_1103_p2 <= "0" when (tmp_24_fu_1093_p4 = ap_const_lv2_0) else "1";
    icmp_ln149_6_fu_1157_p2 <= "0" when (tmp_26_fu_1147_p4 = ap_const_lv2_0) else "1";
    icmp_ln149_7_fu_1211_p2 <= "0" when (tmp_28_fu_1201_p4 = ap_const_lv2_0) else "1";
    icmp_ln149_fu_833_p2 <= "0" when (tmp_14_fu_823_p4 = ap_const_lv2_0) else "1";
    icmp_ln850_10_fu_743_p2 <= "1" when (signed(shl_ln1118_s_fu_721_p3) < signed(ap_const_lv26_3FFFFF1)) else "0";
    icmp_ln850_4_fu_311_p2 <= "1" when (signed(shl_ln1118_4_fu_289_p3) < signed(ap_const_lv26_3FFFFF1)) else "0";
    icmp_ln850_5_fu_383_p2 <= "1" when (signed(shl_ln1118_5_fu_361_p3) < signed(ap_const_lv26_3FFFFF1)) else "0";
    icmp_ln850_6_fu_455_p2 <= "1" when (signed(shl_ln1118_6_fu_433_p3) < signed(ap_const_lv26_3FFFFF1)) else "0";
    icmp_ln850_7_fu_527_p2 <= "1" when (signed(shl_ln1118_7_fu_505_p3) < signed(ap_const_lv26_3FFFFF1)) else "0";
    icmp_ln850_8_fu_599_p2 <= "1" when (signed(shl_ln1118_8_fu_577_p3) < signed(ap_const_lv26_3FFFFF1)) else "0";
    icmp_ln850_9_fu_671_p2 <= "1" when (signed(shl_ln1118_9_fu_649_p3) < signed(ap_const_lv26_3FFFFF1)) else "0";
    icmp_ln850_fu_239_p2 <= "1" when (signed(shl_ln_fu_217_p3) < signed(ap_const_lv26_3FFFFF1)) else "0";
    icmp_ln851_1_fu_329_p2 <= "1" when (p_Result_4_1_fu_321_p3 = ap_const_lv10_0) else "0";
    icmp_ln851_2_fu_401_p2 <= "1" when (p_Result_4_2_fu_393_p3 = ap_const_lv10_0) else "0";
    icmp_ln851_3_fu_473_p2 <= "1" when (p_Result_4_3_fu_465_p3 = ap_const_lv10_0) else "0";
    icmp_ln851_4_fu_545_p2 <= "1" when (p_Result_4_4_fu_537_p3 = ap_const_lv10_0) else "0";
    icmp_ln851_5_fu_617_p2 <= "1" when (p_Result_4_5_fu_609_p3 = ap_const_lv10_0) else "0";
    icmp_ln851_6_fu_689_p2 <= "1" when (p_Result_4_6_fu_681_p3 = ap_const_lv10_0) else "0";
    icmp_ln851_7_fu_761_p2 <= "1" when (p_Result_4_7_fu_753_p3 = ap_const_lv10_0) else "0";
    icmp_ln851_fu_257_p2 <= "1" when (p_Result_4_fu_249_p3 = ap_const_lv10_0) else "0";
    p_Result_4_1_fu_321_p3 <= (trunc_ln851_4_fu_317_p1 & ap_const_lv6_0);
    p_Result_4_2_fu_393_p3 <= (trunc_ln851_5_fu_389_p1 & ap_const_lv6_0);
    p_Result_4_3_fu_465_p3 <= (trunc_ln851_6_fu_461_p1 & ap_const_lv6_0);
    p_Result_4_4_fu_537_p3 <= (trunc_ln851_7_fu_533_p1 & ap_const_lv6_0);
    p_Result_4_5_fu_609_p3 <= (trunc_ln851_8_fu_605_p1 & ap_const_lv6_0);
    p_Result_4_6_fu_681_p3 <= (trunc_ln851_9_fu_677_p1 & ap_const_lv6_0);
    p_Result_4_7_fu_753_p3 <= (trunc_ln851_10_fu_749_p1 & ap_const_lv6_0);
    p_Result_4_fu_249_p3 <= (trunc_ln851_fu_245_p1 & ap_const_lv6_0);
    select_ln148_1_fu_865_p3 <= 
        ap_const_lv12_0 when (tmp_15_fu_857_p3(0) = '1') else 
        add_ln147_9_fu_852_p2;
    select_ln148_2_fu_919_p3 <= 
        ap_const_lv12_0 when (tmp_17_fu_911_p3(0) = '1') else 
        add_ln147_10_fu_906_p2;
    select_ln148_3_fu_973_p3 <= 
        ap_const_lv12_0 when (tmp_19_fu_965_p3(0) = '1') else 
        add_ln147_11_fu_960_p2;
    select_ln148_4_fu_1027_p3 <= 
        ap_const_lv12_0 when (tmp_21_fu_1019_p3(0) = '1') else 
        add_ln147_12_fu_1014_p2;
    select_ln148_5_fu_1081_p3 <= 
        ap_const_lv12_0 when (tmp_23_fu_1073_p3(0) = '1') else 
        add_ln147_13_fu_1068_p2;
    select_ln148_6_fu_1135_p3 <= 
        ap_const_lv12_0 when (tmp_25_fu_1127_p3(0) = '1') else 
        add_ln147_14_fu_1122_p2;
    select_ln148_7_fu_1189_p3 <= 
        ap_const_lv12_0 when (tmp_27_fu_1181_p3(0) = '1') else 
        add_ln147_15_fu_1176_p2;
    select_ln148_fu_811_p3 <= 
        ap_const_lv12_0 when (tmp_12_fu_803_p3(0) = '1') else 
        add_ln147_8_fu_798_p2;
    select_ln149_1_fu_893_p3 <= 
        ap_const_lv10_3FF when (icmp_ln149_1_fu_887_p2(0) = '1') else 
        trunc_ln148_1_fu_873_p1;
    select_ln149_2_fu_947_p3 <= 
        ap_const_lv10_3FF when (icmp_ln149_2_fu_941_p2(0) = '1') else 
        trunc_ln148_2_fu_927_p1;
    select_ln149_3_fu_1001_p3 <= 
        ap_const_lv10_3FF when (icmp_ln149_3_fu_995_p2(0) = '1') else 
        trunc_ln148_3_fu_981_p1;
    select_ln149_4_fu_1055_p3 <= 
        ap_const_lv10_3FF when (icmp_ln149_4_fu_1049_p2(0) = '1') else 
        trunc_ln148_4_fu_1035_p1;
    select_ln149_5_fu_1109_p3 <= 
        ap_const_lv10_3FF when (icmp_ln149_5_fu_1103_p2(0) = '1') else 
        trunc_ln148_5_fu_1089_p1;
    select_ln149_6_fu_1163_p3 <= 
        ap_const_lv10_3FF when (icmp_ln149_6_fu_1157_p2(0) = '1') else 
        trunc_ln148_6_fu_1143_p1;
    select_ln149_7_fu_1217_p3 <= 
        ap_const_lv10_3FF when (icmp_ln149_7_fu_1211_p2(0) = '1') else 
        trunc_ln148_7_fu_1197_p1;
    select_ln149_fu_839_p3 <= 
        ap_const_lv10_3FF when (icmp_ln149_fu_833_p2(0) = '1') else 
        trunc_ln148_fu_819_p1;
    select_ln850_10_fu_781_p3 <= 
        select_ln851_7_fu_773_p3 when (icmp_ln850_10_fu_743_p2(0) = '1') else 
        sext_ln850_10_fu_739_p1;
    select_ln850_4_fu_349_p3 <= 
        select_ln851_1_fu_341_p3 when (icmp_ln850_4_fu_311_p2(0) = '1') else 
        sext_ln850_4_fu_307_p1;
    select_ln850_5_fu_421_p3 <= 
        select_ln851_2_fu_413_p3 when (icmp_ln850_5_fu_383_p2(0) = '1') else 
        sext_ln850_5_fu_379_p1;
    select_ln850_6_fu_493_p3 <= 
        select_ln851_3_fu_485_p3 when (icmp_ln850_6_fu_455_p2(0) = '1') else 
        sext_ln850_6_fu_451_p1;
    select_ln850_7_fu_565_p3 <= 
        select_ln851_4_fu_557_p3 when (icmp_ln850_7_fu_527_p2(0) = '1') else 
        sext_ln850_7_fu_523_p1;
    select_ln850_8_fu_637_p3 <= 
        select_ln851_5_fu_629_p3 when (icmp_ln850_8_fu_599_p2(0) = '1') else 
        sext_ln850_8_fu_595_p1;
    select_ln850_9_fu_709_p3 <= 
        select_ln851_6_fu_701_p3 when (icmp_ln850_9_fu_671_p2(0) = '1') else 
        sext_ln850_9_fu_667_p1;
    select_ln850_fu_277_p3 <= 
        select_ln851_fu_269_p3 when (icmp_ln850_fu_239_p2(0) = '1') else 
        sext_ln850_fu_235_p1;
    select_ln851_1_fu_341_p3 <= 
        sext_ln850_4_fu_307_p1 when (icmp_ln851_1_fu_329_p2(0) = '1') else 
        add_ln700_4_fu_335_p2;
    select_ln851_2_fu_413_p3 <= 
        sext_ln850_5_fu_379_p1 when (icmp_ln851_2_fu_401_p2(0) = '1') else 
        add_ln700_5_fu_407_p2;
    select_ln851_3_fu_485_p3 <= 
        sext_ln850_6_fu_451_p1 when (icmp_ln851_3_fu_473_p2(0) = '1') else 
        add_ln700_6_fu_479_p2;
    select_ln851_4_fu_557_p3 <= 
        sext_ln850_7_fu_523_p1 when (icmp_ln851_4_fu_545_p2(0) = '1') else 
        add_ln700_7_fu_551_p2;
    select_ln851_5_fu_629_p3 <= 
        sext_ln850_8_fu_595_p1 when (icmp_ln851_5_fu_617_p2(0) = '1') else 
        add_ln700_8_fu_623_p2;
    select_ln851_6_fu_701_p3 <= 
        sext_ln850_9_fu_667_p1 when (icmp_ln851_6_fu_689_p2(0) = '1') else 
        add_ln700_9_fu_695_p2;
    select_ln851_7_fu_773_p3 <= 
        sext_ln850_10_fu_739_p1 when (icmp_ln851_7_fu_761_p2(0) = '1') else 
        add_ln700_10_fu_767_p2;
    select_ln851_fu_269_p3 <= 
        sext_ln850_fu_235_p1 when (icmp_ln851_fu_257_p2(0) = '1') else 
        add_ln700_fu_263_p2;
        sext_ln850_10_fu_739_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_2_fu_729_p4),13));

        sext_ln850_4_fu_307_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_9_fu_297_p4),13));

        sext_ln850_5_fu_379_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_1_fu_369_p4),13));

        sext_ln850_6_fu_451_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_3_fu_441_p4),13));

        sext_ln850_7_fu_523_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_5_fu_513_p4),13));

        sext_ln850_8_fu_595_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_7_fu_585_p4),13));

        sext_ln850_9_fu_667_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_s_fu_657_p4),13));

        sext_ln850_fu_235_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_fu_225_p4),13));

    shl_ln1118_4_fu_289_p3 <= (data_1_V_read & ap_const_lv10_0);
    shl_ln1118_5_fu_361_p3 <= (data_2_V_read & ap_const_lv10_0);
    shl_ln1118_6_fu_433_p3 <= (data_3_V_read & ap_const_lv10_0);
    shl_ln1118_7_fu_505_p3 <= (data_4_V_read & ap_const_lv10_0);
    shl_ln1118_8_fu_577_p3 <= (data_5_V_read & ap_const_lv10_0);
    shl_ln1118_9_fu_649_p3 <= (data_6_V_read & ap_const_lv10_0);
    shl_ln1118_s_fu_721_p3 <= (data_7_V_read & ap_const_lv10_0);
    shl_ln_fu_217_p3 <= (data_0_V_read & ap_const_lv10_0);
    sigmoid_table2_address0 <= zext_ln150_fu_1225_p1(10 - 1 downto 0);
    sigmoid_table2_address1 <= zext_ln150_1_fu_1229_p1(10 - 1 downto 0);
    sigmoid_table2_address2 <= zext_ln150_2_fu_1233_p1(10 - 1 downto 0);
    sigmoid_table2_address3 <= zext_ln150_3_fu_1237_p1(10 - 1 downto 0);
    sigmoid_table2_address4 <= zext_ln150_4_fu_1241_p1(10 - 1 downto 0);
    sigmoid_table2_address5 <= zext_ln150_5_fu_1245_p1(10 - 1 downto 0);
    sigmoid_table2_address6 <= zext_ln150_6_fu_1249_p1(10 - 1 downto 0);
    sigmoid_table2_address7 <= zext_ln150_7_fu_1253_p1(10 - 1 downto 0);

    sigmoid_table2_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, ap_ce)
    begin
        if (((ap_const_logic_1 = ap_ce) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            sigmoid_table2_ce0 <= ap_const_logic_1;
        else 
            sigmoid_table2_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    sigmoid_table2_ce1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, ap_ce)
    begin
        if (((ap_const_logic_1 = ap_ce) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            sigmoid_table2_ce1 <= ap_const_logic_1;
        else 
            sigmoid_table2_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    sigmoid_table2_ce2_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, ap_ce)
    begin
        if (((ap_const_logic_1 = ap_ce) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            sigmoid_table2_ce2 <= ap_const_logic_1;
        else 
            sigmoid_table2_ce2 <= ap_const_logic_0;
        end if; 
    end process;


    sigmoid_table2_ce3_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, ap_ce)
    begin
        if (((ap_const_logic_1 = ap_ce) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            sigmoid_table2_ce3 <= ap_const_logic_1;
        else 
            sigmoid_table2_ce3 <= ap_const_logic_0;
        end if; 
    end process;


    sigmoid_table2_ce4_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, ap_ce)
    begin
        if (((ap_const_logic_1 = ap_ce) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            sigmoid_table2_ce4 <= ap_const_logic_1;
        else 
            sigmoid_table2_ce4 <= ap_const_logic_0;
        end if; 
    end process;


    sigmoid_table2_ce5_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, ap_ce)
    begin
        if (((ap_const_logic_1 = ap_ce) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            sigmoid_table2_ce5 <= ap_const_logic_1;
        else 
            sigmoid_table2_ce5 <= ap_const_logic_0;
        end if; 
    end process;


    sigmoid_table2_ce6_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, ap_ce)
    begin
        if (((ap_const_logic_1 = ap_ce) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            sigmoid_table2_ce6 <= ap_const_logic_1;
        else 
            sigmoid_table2_ce6 <= ap_const_logic_0;
        end if; 
    end process;


    sigmoid_table2_ce7_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, ap_ce)
    begin
        if (((ap_const_logic_1 = ap_ce) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            sigmoid_table2_ce7 <= ap_const_logic_1;
        else 
            sigmoid_table2_ce7 <= ap_const_logic_0;
        end if; 
    end process;

    tmp_12_fu_803_p3 <= add_ln147_fu_793_p2(12 downto 12);
    tmp_14_fu_823_p4 <= select_ln148_fu_811_p3(11 downto 10);
    tmp_15_fu_857_p3 <= add_ln147_1_fu_847_p2(12 downto 12);
    tmp_16_fu_877_p4 <= select_ln148_1_fu_865_p3(11 downto 10);
    tmp_17_fu_911_p3 <= add_ln147_2_fu_901_p2(12 downto 12);
    tmp_18_fu_931_p4 <= select_ln148_2_fu_919_p3(11 downto 10);
    tmp_19_fu_965_p3 <= add_ln147_3_fu_955_p2(12 downto 12);
    tmp_1_fu_369_p4 <= data_2_V_read(15 downto 4);
    tmp_20_fu_985_p4 <= select_ln148_3_fu_973_p3(11 downto 10);
    tmp_21_fu_1019_p3 <= add_ln147_4_fu_1009_p2(12 downto 12);
    tmp_22_fu_1039_p4 <= select_ln148_4_fu_1027_p3(11 downto 10);
    tmp_23_fu_1073_p3 <= add_ln147_5_fu_1063_p2(12 downto 12);
    tmp_24_fu_1093_p4 <= select_ln148_5_fu_1081_p3(11 downto 10);
    tmp_25_fu_1127_p3 <= add_ln147_6_fu_1117_p2(12 downto 12);
    tmp_26_fu_1147_p4 <= select_ln148_6_fu_1135_p3(11 downto 10);
    tmp_27_fu_1181_p3 <= add_ln147_7_fu_1171_p2(12 downto 12);
    tmp_28_fu_1201_p4 <= select_ln148_7_fu_1189_p3(11 downto 10);
    tmp_2_fu_729_p4 <= data_7_V_read(15 downto 4);
    tmp_3_fu_441_p4 <= data_3_V_read(15 downto 4);
    tmp_5_fu_513_p4 <= data_4_V_read(15 downto 4);
    tmp_7_fu_585_p4 <= data_5_V_read(15 downto 4);
    tmp_9_fu_297_p4 <= data_1_V_read(15 downto 4);
    tmp_fu_225_p4 <= data_0_V_read(15 downto 4);
    tmp_s_fu_657_p4 <= data_6_V_read(15 downto 4);
    trunc_ln147_1_fu_357_p1 <= select_ln850_4_fu_349_p3(12 - 1 downto 0);
    trunc_ln147_2_fu_429_p1 <= select_ln850_5_fu_421_p3(12 - 1 downto 0);
    trunc_ln147_3_fu_501_p1 <= select_ln850_6_fu_493_p3(12 - 1 downto 0);
    trunc_ln147_4_fu_573_p1 <= select_ln850_7_fu_565_p3(12 - 1 downto 0);
    trunc_ln147_5_fu_645_p1 <= select_ln850_8_fu_637_p3(12 - 1 downto 0);
    trunc_ln147_6_fu_717_p1 <= select_ln850_9_fu_709_p3(12 - 1 downto 0);
    trunc_ln147_7_fu_789_p1 <= select_ln850_10_fu_781_p3(12 - 1 downto 0);
    trunc_ln147_fu_285_p1 <= select_ln850_fu_277_p3(12 - 1 downto 0);
    trunc_ln148_1_fu_873_p1 <= select_ln148_1_fu_865_p3(10 - 1 downto 0);
    trunc_ln148_2_fu_927_p1 <= select_ln148_2_fu_919_p3(10 - 1 downto 0);
    trunc_ln148_3_fu_981_p1 <= select_ln148_3_fu_973_p3(10 - 1 downto 0);
    trunc_ln148_4_fu_1035_p1 <= select_ln148_4_fu_1027_p3(10 - 1 downto 0);
    trunc_ln148_5_fu_1089_p1 <= select_ln148_5_fu_1081_p3(10 - 1 downto 0);
    trunc_ln148_6_fu_1143_p1 <= select_ln148_6_fu_1135_p3(10 - 1 downto 0);
    trunc_ln148_7_fu_1197_p1 <= select_ln148_7_fu_1189_p3(10 - 1 downto 0);
    trunc_ln148_fu_819_p1 <= select_ln148_fu_811_p3(10 - 1 downto 0);
    trunc_ln851_10_fu_749_p1 <= data_7_V_read(4 - 1 downto 0);
    trunc_ln851_4_fu_317_p1 <= data_1_V_read(4 - 1 downto 0);
    trunc_ln851_5_fu_389_p1 <= data_2_V_read(4 - 1 downto 0);
    trunc_ln851_6_fu_461_p1 <= data_3_V_read(4 - 1 downto 0);
    trunc_ln851_7_fu_533_p1 <= data_4_V_read(4 - 1 downto 0);
    trunc_ln851_8_fu_605_p1 <= data_5_V_read(4 - 1 downto 0);
    trunc_ln851_9_fu_677_p1 <= data_6_V_read(4 - 1 downto 0);
    trunc_ln851_fu_245_p1 <= data_0_V_read(4 - 1 downto 0);
    zext_ln150_1_fu_1229_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln149_1_reg_1422),64));
    zext_ln150_2_fu_1233_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln149_2_reg_1427),64));
    zext_ln150_3_fu_1237_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln149_3_reg_1432),64));
    zext_ln150_4_fu_1241_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln149_4_reg_1437),64));
    zext_ln150_5_fu_1245_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln149_5_reg_1442),64));
    zext_ln150_6_fu_1249_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln149_6_reg_1447),64));
    zext_ln150_7_fu_1253_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln149_7_reg_1452),64));
    zext_ln150_fu_1225_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln149_reg_1417),64));
    zext_ln703_1_fu_1261_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sigmoid_table2_q1),16));
    zext_ln703_2_fu_1265_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sigmoid_table2_q2),16));
    zext_ln703_3_fu_1269_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sigmoid_table2_q3),16));
    zext_ln703_4_fu_1273_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sigmoid_table2_q4),16));
    zext_ln703_5_fu_1277_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sigmoid_table2_q5),16));
    zext_ln703_6_fu_1281_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sigmoid_table2_q6),16));
    zext_ln703_7_fu_1285_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sigmoid_table2_q7),16));
    zext_ln703_fu_1257_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sigmoid_table2_q0),16));
end behav;
